### ISSUE TITLE
doh.padQuery: nil ptr in miekg/dns:defaults.go:152

### ISSUE THREAD

**Issue by ignoramous** [celzero/firestack#111]
Related: #96 

```bash
# 11-03 05:50:57.349 32129 20730 E LibLogger: github.com/celzero/firestack/intra/log.(*simpleLogger).Stack(0x40001681c0, 0x0, {0x4000606230?, 0x40002ac4b0?}, {0x40022dc000, 0x80000, 0x80000})
# 11-03 05:50:57.349 32129 20730 E LibLogger: >---/home/jitpack/build/intra/log/logger.go:398 +0x2c8
# 11-03 05:50:57.349 32129 20730 E LibLogger: github.com/celzero/firestack/intra/log.C({0x40002ac4b0, 0x4e}, {0x40022dc000, 0x80000, 0x80000})
# 11-03 05:50:57.349 32129 20730 E LibLogger: >---/home/jitpack/build/intra/log/log.go:139 +0xf8
# 11-03 05:50:57.349 32129 20730 E LibLogger: github.com/celzero/firestack/intra/core.trace(0x40001681c0?, {0x40002ac4b0, 0x4e})
# 11-03 05:50:57.349 32129 20730 E LibLogger: >---/home/jitpack/build/intra/core/dontpanic.go:101 +0x19c
# 11-03 05:50:57.349 32129 20730 E LibLogger: github.com/celzero/firestack/intra/core.Recover(0x0, {0x763806052f, 0x8})
# 11-03 05:50:57.349 32129 20730 E LibLogger: >---/home/jitpack/build/intra/core/dontpanic.go:74 +0x13c
11-03 05:50:57.349 32129 20730 E LibLogger: panic({0x763892d0c0?, 0x7638f537d0?})
11-03 05:50:57.349 32129 20730 E LibLogger: >---/home/jitpack/golang/go/src/runtime/panic.go:785 +0x124
11-03 05:50:57.349 32129 20730 E LibLogger: github.com/miekg/dns.(*Msg).IsEdns0(0x40008b9710)
11-03 05:50:57.349 32129 20730 E LibLogger: >---/tmp/gomobile-work-1841608193/pkg/mod/github.com/miekg/dns@v1.1.62/defaults.go:152 +0x60
11-03 05:50:57.349 32129 20730 E LibLogger: github.com/celzero/firestack/intra/xdns.ensureEDNS0(0x40008b9710)
11-03 05:50:57.349 32129 20730 E LibLogger: >---/home/jitpack/build/intra/xdns/dnsutil.go:480 +0x20
11-03 05:50:57.349 32129 20730 E LibLogger: github.com/celzero/firestack/intra/xdns.AddEDNS0PaddingIfNoneFound(0x40008b9710)
11-03 05:50:57.349 32129 20730 E LibLogger: >---/home/jitpack/build/intra/xdns/dnsutil.go:517 +0x24
11-03 05:50:57.349 32129 20730 E LibLogger: github.com/celzero/firestack/intra/doh.padQuery(0x40008b9710)
11-03 05:50:57.349 32129 20730 E LibLogger: >---/home/jitpack/build/intra/doh/padding.go:35 +0x40
11-03 05:50:57.349 32129 20730 E LibLogger: github.com/celzero/firestack/intra/doh.(*transport).doDoh(0x40003dc160, {0x4000f84bdc, 0x4}, 0x40008b9710)
11-03 05:50:57.349 32129 20730 E LibLogger: >---/home/jitpack/build/intra/doh/doh.go:372 +0x44
11-03 05:50:57.349 32129 20730 E LibLogger: github.com/celzero/firestack/intra/doh.(*transport).Query(0x40003dc160, {0x4000f84bd8, 0x8}, 0x40008b9710, 0x4000ec2600)
11-03 05:50:57.349 32129 20730 E LibLogger: >---/home/jitpack/build/intra/doh/doh.go:679 +0xa8
11-03 05:50:57.349 32129 20730 E LibLogger: github.com/celzero/firestack/intra/dnsx.Req({0x7638a462f0, 0x40003dc160}, {0x4000f84bd8, 0x8}, 0x40008b9710, 0x4000ec2600)
11-03 05:50:57.349 32129 20730 E LibLogger: >---/home/jitpack/build/intra/dnsx/alg.go:1129 +0x12c
# 11-03 05:50:57.349 32129 20730 E LibLogger: github.com/celzero/firestack/intra/dnsx.(*ctransport).fetch.func1.1()
# 11-03 05:50:57.349 32129 20730 E LibLogger: >---/home/jitpack/build/intra/dnsx/cacher.go:344 +0x60
# 11-03 05:50:57.349 32129 20730 E LibLogger: github.com/celzero/firestack/intra/core.(*Barrier[...]).Do.func1()
# 11-03 05:50:57.349 32129 20730 E LibLogger: >---/home/jitpack/build/intra/core/barrier.go:194 +0x30
# 11-03 05:50:57.349 32129 20730 E LibLogger: github.com/celzero/firestack/intra/core.Grx[...].func1()
# 11-03 05:50:57.349 32129 20730 E LibLogger: >---/home/jitpack/build/intra/core/async.go:79 +0x94
# 11-03 05:50:57.349 32129 20730 E LibLogger: created by github.com/celzero/firestack/intra/core.Grx[...] in goroutine 281226
# 11-03 05:50:57.349 32129 20730 E LibLogger: >---/home/jitpack/build/intra/core/async.go:75 +0x110

```

**Comment by hussainmohd-a** [comment]
```jsx
VV doh: sending query to: sky.rethinkdns.com
VV doh: using proxy Base:127.8.4.5:3690 ech? true / other? true
V doh: got-conn({0x40006aae08 true false 0s})
VV ns: tun(159): WritePackets (to tun): written(1)/total(1)
VV doh: wrote-req({<nil>})
VV ns: tun(159): dispatch: got(91 bytes), err(errno 0)
VV ns: tun(159): forwarder: q on proc 1, 2048 | :60158 => :443
VV ns: tun(159): dispatch: done? false
VV ns: tun(159): dispatch: got(211 bytes), err(errno 0)
VV ns: tun(159): forwarder: q on proc 1, 2048 | :60158 => :443
VV ns: tun(159): dispatch: done? false
VV ns: tun(159): inject-inbound (from tun) 2048
VV ns: tun(159): inject-inbound (from tun) 2048
VV ns: tun(159): WritePackets (to tun): written(1)/total(1)
E ;; opcode: QUERY, status: NOERROR, id: 0
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version 0; flags:; udp: 4096
; PADDING: 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

;; QUESTION SECTION:
;github.com.	IN	 HTTPS
 [0] runtime error: invalid memory address or nil pointer dereference

E ----START----
09 November 2024, 00:59:40: F ;; opcode: QUERY, status: NOERROR, id: 0
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version 0; flags:; udp: 4096
; PADDING: 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

;; QUESTION SECTION:
;github.com.	IN	 HTTPS
 [0] runtime error: invalid memory address or nil pointer dereference
 (#1)
09 November 2024, 00:59:40: goroutine 64176 [running]:
github.com/celzero/firestack/intra/log.(*simpleLogger).Stack(0x40001ba1c0, 0x0, {0x4000162960?, 0x40001623c0?}, {0x4000f1e000, 0x80000, 0x80000})
	/home/jitpack/build/intra/log/logger.go:398 +0x2c8
github.com/celzero/firestack/intra/log.C({0x40001623c0, 0x1cd}, {0x4000f1e000, 0x80000, 0x80000})
	/home/jitpack/build/intra/log/log.go:139 +0xf8
github.com/celzero/firestack/intra/core.trace(0x40001ba1c0?, {0x40001623c0, 0x1cd})
	/home/jitpack/build/intra/core/dontpanic.go:101 +0x19c
github.com/celzero/firestack/intra/core.Recover(0x0, {0x763fe52ca0, 0x40007ce120})
	/home/jitpack/build/intra/core/dontpanic.go:74 +0x130
panic({0x763fd64600?, 0x764038f3b0?})
	/home/jitpack/golang/go/src/runtime/panic.go:785 +0x124
github.com/miekg/dns.(*OPT).len(0x4000a97e00, 0xb?, 0xc?)
	/tmp/gomobile-work-203333035/pkg/mod/github.com/miekg/dns@v1.1.62/edns.go:135 +0x64
github.com/miekg/dns.msgLenWithCompressionMap(0x40007ce120, 0x0)
	/tmp/gomobile-work-203333035/pkg/mod/github.com/miekg/dns@v1.1.62/msg.go:998 +0x1a8
github.com/miekg/dns.(*Msg).Len(0x40001ba140?)
	/tmp/gomobile-work-203333035/pkg/mod/github.com/miekg/dns@v1.1.62/msg.go:977 +0x6c
github.com/celzero/firestack/intra/xdns.ComputePaddingSize(0x40007ce120?)
	/home/jitpack/build/intra/xdns/dnsutil.go:504 +0x20
github.com/celzero/firestack/intra/xdns.AddEDNS0PaddingIfNoneFound(0x40007ce120)
	/home/jitpack/build/intra/xdns/dnsutil.go:526 +0xbc
github.com/celzero/firestack/intra/doh.padQuery(0x40004a1cd8?)
	/home/jitpack/build/intra/doh/padding.go:35 +0x50
github.com/celzero/firestack/intra/doh.(*transport).doDoh(0x40003462c0, {0x763f490dd3, 0x4}, 0x40007ce120)
	/home/jitpack/build/intra/doh/doh.go:390 +0x44
github.com/celzero/firestack/intra/doh.(*transport).Query(0x40003462c0, {0x40002a41d8, 0x8}, 0x40007ce120, 0x40007955c0)
	/home/jitpack/build/intra/doh/doh.go:733 +0xc8
github.com/celzero/firestack/intra/dnsx.Req({0x763fe7ed90, 0x40003462c0}, {0x40002a41d8, 0x8}, 0x40007ce120, 0x40007955c0)
	/home/jitpack/build/intra/dnsx/alg.go:1278 +0x12c
github.com/celzero/firestack/intra/dnsx.(*ctransport).fetch.func1.1()
	/home/jitpack/build/intra/dnsx/cacher.go:344 +0x60
github.com/celzero/firestack/intra/core.(*Barrier[...]).Do.func1()
	/home/jitpack/build/intra/core/barrier.go:194 +0x30
github.com/celzero/firestack/intra/core.Grx[...].func1()
	/home/jitpack/build/intra/core/async.go:79 +0xbc
created by github.com/celzero/firestack/intra/core.Grx[...] in goroutine 64175
	/home/jitpack/build/intra/core/async.go:75 +0x110
```

**Comment by ignoramous** [comment]
Upstream won't fix. Don't use padding.
