### ISSUE TITLE
Exception While Setting New System DNS Proxy

### ISSUE THREAD

**Issue by hussainmohd-a** [celzero/firestack#30]
Logs

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7826a6a6c0]

goroutine 35 [running, locked to thread]:
github.com/celzero/firestack/intra/dns53.newTransport({0x78265598fc, 0x6}, 0x4000316070, {0x0, 0x0})
	/home/jitpack/build/intra/dns53/upstream.go:62 +0x30
github.com/celzero/firestack/intra/dns53.NewTransportFrom({0x78265598fc, 0x6}, {{{0x782663d5f0?, 0x1?}, 0x40001a0000?}, 0x5730?}, {0x0, 0x0})
	/home/jitpack/build/intra/dns53/upstream.go:100 +0x78
github.com/celzero/firestack/intra.newSystemDNSProxy(...)
	/home/jitpack/build/intra/dns.go:31
github.com/celzero/firestack/intra.(*rtunnel).SetSystemDNS(0x40002ba230, {0x4000274020?, 0x40ffffffdf?})
	/home/jitpack/build/intra/tunnel.go:181 +0x2bc
main.proxyintra_Tunnel_SetSystemDNS(0x180000?, {0x7889cf3980, 0xe, {0x0, 0x0, 0x0, 0x0}})
	/tmp/gomobile-work-1593204056/src/gobind/go_intramain.go:851 +0x6c
Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 29021 (DefaultDispatch), pid 26820 (elzero.bravedns)
pid: 26820, tid: 29021, name: DefaultDispatch  >>> com.celzero.bravedns <<<
```

**Comment by ignoramous** [comment]
https://github.com/celzero/firestack/commit/dcaa3eecc3f4d0be7d17244ef9e27e5630d8e0c3
