### ISSUE TITLE
Failed to set endpoint error while adding WireGuard proxy

### ISSUE THREAD

**Issue by hussainmohd-a** [celzero/firestack#37]
```
ipmapper.go:114: E ipmapper: lookup: yul-359-wg.whiskergalaxy.com: err read udp 10.1.204.164:58215->10.1.10.253:53: i/o timeout
  ipmap.go:212: W ipmap: Add: err resolving yul-359-wg.whiskergalaxy.com: read udp 10.1.204.164:58215->10.1.10.253:53: i/o timeout
  ipmap.go:119: W ipmap: Get: zero ips for yul-359-wg.whiskergalaxy.com
  multihost.go:73: W multihost: no ips for "yul-359-wg.whiskergalaxy.com"
  wgconn.go:82: E wg: bind: wg3 not a valid endpoint in(yul-359-wg.whiskergalaxy.com:443); out([yul-359-wg.whiskergalaxy.com], [])
  uapi.go:148: E wg:wg3 IPC error -22: failed to set endpoint yul-359-wg.whiskergalaxy.com:443: wg: bind: no endpoint
  wgproxy.go:340: E proxy: wg: failed to ipc-set IPC error -22: failed to set endpoint yul-359-wg.whiskergalaxy.com:443: wg: bind: no endpoint
  wgconn.go:82: E wg: bind: wg3 not a valid endpoint in(yul-359-wg.whiskergalaxy.com:443); out([yul-359-wg.whiskergalaxy.com], [])
  uapi.go:148: E wg:wg3 IPC error -22: failed to set endpoint yul-359-wg.whiskergalaxy.com:443: wg: bind: no endpoint
  error adding wireguard proxy: IPC error -22: failed to set endpoint yul-359-wg.whiskergalaxy.com:443: wg: bind: no endpoint
  go.Universe$proxyerror: IPC error -22: failed to set endpoint yul-359-wg.whiskergalaxy.com:443: wg: bind: no endpoint
  	at backend.Backend$proxyProxies.addProxy(Native Method)
  	at com.celzero.bravedns.net.go.GoVpnAdapter.addWgProxy(GoVpnAdapter.kt:647)
  	at com.celzero.bravedns.service.BraveVPNService$addWireGuardProxy$1.invokeSuspend(BraveVPNService.kt:2881)
  	at com.celzero.bravedns.service.BraveVPNService$addWireGuardProxy$1.invoke(Unknown Source:8)
  	at com.celzero.bravedns.service.BraveVPNService$addWireGuardProxy$1.invoke(Unknown Source:2)
  	at com.celzero.bravedns.service.BraveVPNService$io$1.invokeSuspend(BraveVPNService.kt:2335)
  	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
  	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
  	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
  	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
  	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
  wgproxy.go:340: E proxy: wg: failed to ipc-set IPC error -22: failed to set endpoint yul-359-wg.whiskergalaxy.com:443: wg: bind: no endpoint
```

**Comment by ignoramous** [comment]
This happens when wgproxy fails to resolve hostnames. Retrying using UI is one way out.

**Comment by ignoramous** [comment]
On zero answer / other failures, `dnsx.Resolver.LocalLookup` retries once using `System DNS`.
