### ISSUE TITLE
nil pointer at ipn.StdNetBind2.receiveIP

### ISSUE THREAD

**Issue by hussainmohd-a** [celzero/firestack#40]
```
Go                      com.celzero.bravedns                 E  panic: runtime error: invalid memory address or nil pointer dereference
Go                      com.celzero.bravedns                 E  [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x75ec13d3a4]
Go                      com.celzero.bravedns                 E  
GoLog                   com.celzero.bravedns                 E  panic: runtime error: invalid memory address or nil pointer dereference
Go                      com.celzero.bravedns                 E  goroutine 2766 [running]:
Go                      com.celzero.bravedns                 E  golang.org/x/net/ipv6.(*PacketConn).ReadBatch(0x40003c8a90?, {0x4008ab8008?, 0x4008b91ac8?, 0x75ebed8b88?}, 0x4008b91a98?)
Go                      com.celzero.bravedns                 E  	<autogenerated>:1 +0x24
Go                      com.celzero.bravedns                 E  github.com/celzero/firestack/intra/ipn/wg.(*StdNetBind2).receiveIP(0x40003c8a90, {0x75ec566aa0, 0x0}, 0x6?, 0x0, {0x4008872008, 0x80, 0x4017390000?}, {0x4007e24400, 0x80, ...}, ...)
Go                      com.celzero.bravedns                 E  	/home/jitpack/build/intra/ipn/wg/wgconn2.go:347 +0x718
Go                      com.celzero.bravedns                 E  github.com/celzero/firestack/intra/ipn/wg.(*StdNetBind2).Open.(*StdNetBind2).makeReceiveIPv6.func2({0x4008872008?, 0x2?, 0x4009118020?}, {0x4007e24400?, 0x1?, 0x0?}, {0x40089f6008?, 0x0?, 0x0?})
Go                      com.celzero.bravedns                 E  	/home/jitpack/build/intra/ipn/wg/wgconn2.go:391 +0x74
Go                      com.celzero.bravedns                 E  golang.zx2c4.com/wireguard/device.(*Device).RoutineReceiveIncoming(0x4008e9ea08, 0x80, 0x4008fd6880)
Go                      com.celzero.bravedns                 E  	/tmp/gomobile-work-4110023306/pkg/mod/golang.zx2c4.com/wireguard@v0.0.0-20231211153847-12269c276173/device/receive.go:111 +0x2cc
Go                      com.celzero.bravedns                 E  created by golang.zx2c4.com/wireguard/device.(*Device).BindUpdate in goroutine 18
Go                      com.celzero.bravedns                 E  	/tmp/gomobile-work-4110023306/pkg/mod/golang.zx2c4.com/wireguard@v0.0.0-20231211153847-12269c276173/device/device.go:524 +0x30c

VpnLifecycle            com.celzero.bravedns                 D  r6: underlyingNetworks: true, 0
libc                    com.celzero.bravedns                 A  Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 5401 (Thread-21), pid 24414 (elzero.bravedns)
```

**Comment by hussainmohd-a** [comment]
```
GoLog                   com.celzero.bravedns                 E  wgproxy.go:513: W wg: wg7 tun: read closed
elzero.bravedn          com.celzero.bravedns                 W  0xebadde09 skipped times: 0
Go                      com.celzero.bravedns                 E  panic: runtime error: invalid memory address or nil pointer dereference
Go                      com.celzero.bravedns                 E  [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x75ec43e644]
Go                      com.celzero.bravedns                 E  
Go                      com.celzero.bravedns                 E  goroutine 7481 [running]:
Go                      com.celzero.bravedns                 E  golang.org/x/net/ipv6.(*PacketConn).ReadBatch(0x400baa6680?, {0x400b896008?, 0x4009e57ac8?, 0x75ec1d7fc0?}, 0x4009e57ac8?)
Go                      com.celzero.bravedns                 E  	<autogenerated>:1 +0x24
Go                      com.celzero.bravedns                 E  github.com/celzero/firestack/intra/ipn/wg.(*StdNetBind2).receiveIP(0x400baa6680, {0x75ec868320, 0x0}, 0x0, 0x0, {0x400a7fa008, 0x80, 0x0?}, {0x4009ccb000, 0x80, ...}, ...)
Go                      com.celzero.bravedns                 E  	/home/jitpack/build/intra/ipn/wg/wgconn2.go:350 +0x71c
Go                      com.celzero.bravedns                 E  github.com/celzero/firestack/intra/ipn/wg.(*StdNetBind2).Open.(*StdNetBind2).makeReceiveIPv6.func2({0x400a7fa008?, 0x2?, 0x400c36cbc0?}, {0x4009ccb000?, 0x1?, 0x75ecc6b1d0?}, {0x400b93f208?, 0x4009cc70c0?, 0x400f1e97f8?})
Go                      com.celzero.bravedns                 E  	/home/jitpack/build/intra/ipn/wg/wgconn2.go:394 +0x74
Go                      com.celzero.bravedns                 E  golang.zx2c4.com/wireguard/device.(*Device).RoutineReceiveIncoming(0x400b9f4508, 0x80, 0x400c36cb80)
Go                      com.celzero.bravedns                 E  	/tmp/gomobile-work-3367998529/pkg/mod/golang.zx2c4.com/wireguard@v0.0.0-20231211153847-12269c276173/device/receive.go:111 +0x2cc
Go                      com.celzero.bravedns                 E  created by golang.zx2c4.com/wireguard/device.(*Device).BindUpdate in goroutine 7505

Go                      com.celzero.bravedns                 E  	/tmp/gomobile-work-3367998529/pkg/mod/golang.zx2c4.com/wireguard@v0.0.0-20231211153847-12269c276173/device/device.go:524 +0x30c
libc                    com.celzero.bravedns                 A  Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 22559 (Thread-18), pid 7726 (elzero.bravedns)
DEBUG                   pid-26727                            A  pid: 7726, tid: 22559, name: Thread-18  >>> com.celzero.bravedns <<<
DEBUG                   pid-26727                            A        #00 pc 00000000002ee348  /data/app/com.celzero.bravedns-W1M_T0g6KFwgeEQ7Xiez6Q==/base.apk (offset 0x7c2000)
```
