### ISSUE TITLE
Nil ptr in cacher.go:cres.copy()

### ISSUE THREAD

**Issue by ignoramous** [celzero/firestack#49]
```
04-27 23:35:30.818 20956 21115 D MobileSignalIconsSelector: getINUDataIconGroup(): 13
04-27 23:35:31.107 15992 17431 I GoLog   : base.go:49: I proxy: base: dial(tcp) to 213.196.191.96:8443; err? <nil>
04-27 23:35:31.377 15992 17431 E GoLog   : multiserver.go:177: E dnscrypt: tcp: read(enc) Preferred:2.dnscrypt-cert.scaleway-ams/51.15.122.250:443<=>213.196.191.96:8443 err EOF
04-27 23:35:31.377 15992 17431 E GoLog   : multiserver.go:265: W dnscrypt: querying [udp? false; tcpfallback?: true] failed: EOF
04-27 23:35:31.380 15992     0 E Go      : panic: runtime error: invalid memory address or nil pointer dereference
...
04-27 23:35:31.380 15992     0 E Go      : [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x77a0e2c8f0]
04-27 23:35:31.380 15992     0 E Go      :                                      
04-27 23:35:31.380 15992     0 E Go      : goroutine 98 [running]:              
04-27 23:35:31.381 15992     0 E Go      : github.com/miekg/dns.(*Msg).CopyTo(0x0, 0x4000208ab0)
04-27 23:35:31.381 15992     0 E Go      : >/tmp/gomobile-work-2330865102/pkg/mod/github.com/miekg/dns@v1.1.49/msg.go:1059 +0x20
04-27 23:35:31.381 15992     0 E Go      : github.com/miekg/dns.(*Msg).Copy(...)
04-27 23:35:31.381 15992     0 E Go      : >/tmp/gomobile-work-2330865102/pkg/mod/github.com/miekg/dns@v1.1.49/msg.go:1055
04-27 23:35:31.381 15992     0 E Go      : github.com/celzero/firestack/intra/dnsx.(*cres).copy(0x4007cdf440)
04-27 23:35:31.381 15992     0 E Go      : >/home/jitpack/build/intra/dnsx/cacher.go:125 +0x3c
04-27 23:35:31.381 15992     0 E Go      : github.com/celzero/firestack/intra/dnsx.(*ctransport).fetch.func1(0x400021a0b0)
04-27 23:35:31.381 15992     0 E Go      : >/home/jitpack/build/intra/dnsx/cacher.go:334 +0x310
04-27 23:35:31.382 15992     0 E Go      : github.com/celzero/firestack/intra/dnsx.(*ctransport).fetch(0x4007e00000, {0x4000198aa8, 0x8}, {0x4007bc0000, 0x22, 0x800}, 0x40001d6360, 0x400021a0b0, 0x4007bcf3b0, {0x4007c0e198, ...})
04-27 23:35:31.382 15992     0 E Go      : >/home/jitpack/build/intra/dnsx/cacher.go:402 +0x624
04-27 23:35:31.383 15992     0 E Go      : github.com/celzero/firestack/intra/dnsx.(*ctransport).Query(0x4007e00000, {0x4000198aa8, 0x8}, {0x4007bc0000, 0x22, 0x800}, 0x400021a0b0)
04-27 23:35:31.383 15992     0 E Go      : >/home/jitpack/build/intra/dnsx/cacher.go:428 +0x1d0
04-27 23:35:31.383 15992     0 E Go      : github.com/celzero/firestack/intra/dnsx.Req({0x77a1267728?, 0x4007e00000?}, {0x4000198aa8?, 0x0?}, {0x4007bc0000?, 0x4000044f08?, 0x0?}, 0x0?)
04-27 23:35:31.383 15992     0 E Go      : >/home/jitpack/build/intra/dnsx/alg.go:899 +0xa4
04-27 23:35:31.384 15992     0 E Go      : github.com/celzero/firestack/intra/dnsx.(*dnsgateway).q(0x4000208120, {0x77a1267728, 0x4007e00000}, {0x0, 0x0}, {0x400012c020, 0x0, 0x1}, {0x4000198aa8, 0x8}, ...)
04-27 23:35:31.384 15992     0 E Go      : >/home/jitpack/build/intra/dnsx/alg.go:255 +0x200
04-27 23:35:31.384 15992     0 E Go      : github.com/celzero/firestack/intra/dnsx.(*resolver).forward(0x40001300b0, {0x4007bc0000, 0x22, 0x800}, {0x0, 0x0, 0x0})
04-27 23:35:31.385 15992     0 E Go      : >/home/jitpack/build/intra/dnsx/transport.go:387 +0xa60
04-27 23:35:31.385 15992     0 E Go      : github.com/celzero/firestack/intra/dnsx.(*resolver).dnsudp(0x77a1671790?, {0x4007bc0000?, 0x400018e060?, 0x4000120840?}, {0x779eb094b8, 0x4007e0c000})
04-27 23:35:31.385 15992     0 E Go      : >/home/jitpack/build/intra/dnsx/transport.go:520 +0x38
04-27 23:35:31.385 15992     0 E Go      : github.com/celzero/firestack/intra/dnsx.(*resolver).reply.func2()
04-27 23:35:31.385 15992     0 E Go      : >/home/jitpack/build/intra/dnsx/transport.go:560 +0x74
04-27 23:35:31.385 15992     0 E Go      : created by github.com/celzero/firestack/intra/dnsx.(*resolver).reply in goroutine 120
04-27 23:35:31.385 15992     0 E Go      : >/home/jitpack/build/intra/dnsx/transport.go:570 +0x7c
04-27 23:35:31.386 15992 17427 F libc    : Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 17427 (Thread-19), pid 15992 (elzero.bravedns)
04-27 23:35:31.400 20589 20890 D SemWifiApTrafficPoller: received START_TRAFFIC_CHECK
04-27 23:35:31.552 17473 17473 I crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstone
04-27 23:35:31.553   675   675 I tombstoned: received crash request for pid 17427
04-27 23:35:31.562 17473 17473 I crash_dump64: performing dump of process 15992 (target tid = 17427)
04-27 23:35:31.571 17473 17473 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-27 23:35:31.571 17473 17473 F DEBUG   : Revision: '12'                       
04-27 23:35:31.571 17473 17473 F DEBUG   : ABI: 'arm64'                         
04-27 23:35:31.571 17473 17473 F DEBUG   : Timestamp: 2024-04-27 23:35:31+0530  
04-27 23:35:31.571 17473 17473 F DEBUG   : pid: 15992, tid: 17427, name: Thread-19  >>> com.celzero.bravedns <<<
04-27 23:35:31.571 17473 17473 F DEBUG   : uid: 12614                           
04-27 23:35:31.571 17473 17473 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
04-27 23:35:31.571 17473 17473 F DEBUG   :     x0  0000000000000000  x1  0000000000004413  x2  0000000000000006  x3  0000000000000008
04-27 23:35:31.571 17473 17473 F DEBUG   :     x4  0000000000000001  x5  0000000000000001  x6  0000000000000000  x7  000000000000000a
04-27 23:35:31.571 17473 17473 F DEBUG   :     x8  0000000000000083  x9  0000000000000037  x10 0000000000000001  x11 00000077a135975f
04-27 23:35:31.571 17473 17473 F DEBUG   :     x12 000000000000000b  x13 00000077a0aff218  x14 0000000000000116  x15 0000000000000117
04-27 23:35:31.572 17473 17473 F DEBUG   :     x16 000000779ec23360  x17 000000779ed1a810  x18 00000076ed00a000  x19 0000000000003e78
04-27 23:35:31.572 17473 17473 F DEBUG   :     x20 000000779ed1a6b0  x21 0000004000065008  x22 0000000000000028  x23 0000000000004411
04-27 23:35:31.572 17473 17473 F DEBUG   :     x24 000000779ed1acc0  x25 000000400029cf30  x26 0000000000000000  x27 0000000000000010
04-27 23:35:31.572 17473 17473 F DEBUG   :     x28 00000040001ae540  x29 00000040001defb8
04-27 23:35:31.572 17473 17473 F DEBUG   :     lr  00000077a0bf3814  sp  00000040001defc0  pc  00000077a0c125e8  pst 0000000080000000
04-27 23:35:31.573 17473 17473 F DEBUG   : backtrace:                           
04-27 23:35:31.573 17473 17473 F DEBUG   :       #00 pc 00000000002f75e8  /data/app/~~OkBOVvxGfS5gUKr5ZwQu8g==/com.celzero.bravedns-pzkJQRvI_MzahcL-YFFTCQ==/base.apk (offset 0x33c000)
```
*Reported by* @ZenzoK90: https://github.com/celzero/rethink-app/issues/1333#issuecomment-2079787783

**Comment by ignoramous** [comment]
fixed: https://github.com/celzero/firestack/commit/2661b9c2f0c9ca3103b9ee3258a1d26e236fb077
