### ISSUE TITLE
Index out of bounds 

### ISSUE THREAD

**Issue by ignoramous** [celzero/firestack#5]
As the blocklist files were being updated, I also concurrently hit the `configure` button and configured a bunch of blocklists from the `rethinkdns.com/configure` webview. After the download was done, the app was stuck in a loop of runtime exceptions pointing to mismatch in configured blocklists (stamp) and the downloaded blocklist files (`filetag.json`). Presumably some data/download race has mangled the `filetag.json`. Either way, the app shouldn't crash and recover from this gracefully and let the users re-download a failed/botched download such as in this case. 

```
08-31 22:16:46.140  5627  5680 I VpnLifecycle: app dns mode is set with local stamp: 1:0N_-PwAQfwD___r_oB02kIAA5AJAoQ==
08-31 22:16:46.143  5627     0 E Go      : panic: runtime error: index out of range [176] with length 175
08-31 22:16:46.143  5627     0 E Go      :                                      
08-31 22:16:46.143  5627     0 E Go      : goroutine 17 [running, locked to thread]:
08-31 22:16:46.143  5627     0 E Go      : github.com/celzero/firestack/intra/dnsx.(*bravedns).flagstotag(0x40000b8000, 0x40001a4040, 0xb, 0xb, 0xb, 0xb, 0x0, 0x0, 0x717ab50792)
08-31 22:16:46.143  5627     0 E Go      : >/home/jitpack/build/intra/dnsx/bravedns.go:370 +0x35c
08-31 22:16:46.143  5627     0 E Go      : github.com/celzero/firestack/intra/dnsx.(*bravedns).decode(0x40000b8000, 0x40000c8602, 0x20, 0x40000c8600, 0x1, 0x1, 0x4000112000, 0x2, 0x2, 0x71eb242a00)
08-31 22:16:46.143  5627     0 E Go      : >/home/jitpack/build/intra/dnsx/bravedns.go:316 +0x1b8
08-31 22:16:46.143  5627     0 E Go      : github.com/celzero/firestack/intra/dnsx.(*bravedns).StampToNames(0x40000b8000, 0x40000c8600, 0x22, 0x40000c8600, 0x22, 0x717ac467a0, 0x22)
08-31 22:16:46.143  5627     0 E Go      : >/home/jitpack/build/intra/dnsx/bravedns.go:98 +0x90
08-31 22:16:46.143  5627     0 E Go      : github.com/celzero/firestack/intra/dnsx.(*bravedns).SetStamp(0x40000b8000, 0x40000c8600, 0x22, 0x22, 0x40000b8000)
08-31 22:16:46.143  5627     0 E Go      : >/home/jitpack/build/intra/dnsx/bravedns.go:78 +0x30
08-31 22:16:46.143  5627     0 E Go      : main.proxydnsx_BraveDNS_SetStamp(0x40ffffffe6, 0x71eb242a00, 0x22, 0xffffffe6)
08-31 22:16:46.143  5627     0 E Go      : >/tmp/gomobile-work-859390173/src/gobind/go_dnsxmain.go:92 +0x84
08-31 22:16:46.143  5627     0 E Go      : main._cgoexpwrap_a8eb34235193_proxydnsx_BraveDNS_SetStamp(0x71ffffffe6, 0x71eb242a00, 0x22, 0x141c0d70)
08-31 22:16:46.143  5627     0 E Go      : >_cgo_gotypes.go:2067 +0x30          
08-31 22:16:46.143  5627  5680 F libc    : Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 5680 (pool-3-thread-1), pid 5627 (elzero.bravedns)
08-31 22:16:46.297  5688  5688 I crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstone
08-31 22:16:46.297  1264  1264 I /system/bin/tombstoned: received crash request for pid 5680
08-31 22:16:46.297  5688  5688 I crash_dump64: performing dump of process 5627 (target tid = 5680)
08-31 22:16:46.304  5688  5688 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
08-31 22:16:46.304  5688  5688 F DEBUG   : Build fingerprint: 'OnePlus/OnePlus6/OnePlus6:10/QKQ1.190716.003/2107132155:user/release-keys'
08-31 22:16:46.304  5688  5688 F DEBUG   : Revision: '0'                        
08-31 22:16:46.304  5688  5688 F DEBUG   : ABI: 'arm64'                         
08-31 22:16:46.304  5688  5688 F DEBUG   : Timestamp: 2021-08-31 22:16:46+0530  
08-31 22:16:46.304  5688  5688 F DEBUG   : pid: 5627, tid: 5680, name: pool-3-thread-1  >>> com.celzero.bravedns <<<
08-31 22:16:46.304  5688  5688 F DEBUG   : uid: 10495                           
08-31 22:16:46.304  5688  5688 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
08-31 22:16:46.304  5688  5688 F DEBUG   :     x0  0000000000000000  x1  0000000000001630  x2  0000000000000006  x3  0000000000000008
08-31 22:16:46.304  5688  5688 F DEBUG   :     x4  0000000000000001  x5  0000000000000000  x6  000000000000000d  x7  0000000000000002
08-31 22:16:46.304  5688  5688 F DEBUG   :     x8  0000000000000083  x9  0000000000000006  x10 0000000000000000  x11 000000717acdd8c0
08-31 22:16:46.304  5688  5688 F DEBUG   :     x12 0000000000000000  x13 0000000000000000  x14 0000000000000000  x15 0000000000000001
08-31 22:16:46.304  5688  5688 F DEBUG   :     x16 000000717a8c44b3  x17 000000717a8c44b0  x18 000000717c26a000  x19 00000000000015fb
08-31 22:16:46.304  5688  5688 F DEBUG   :     x20 000000714b2c7de0  x21 0000004000042000  x22 0000000000000000  x23 00000000141c0d70
08-31 22:16:46.304  5688  5688 F DEBUG   :     x24 000000001418ad38  x25 0000000014186ee0  x26 0000000000000000  x27 0000000000000010
08-31 22:16:46.304  5688  5688 F DEBUG   :     x28 0000004000000600  x29 000000714b2c86e0
08-31 22:16:46.304  5688  5688 F DEBUG   :     sp  00000040002a5a20  lr  000000717a8a9500  pc  000000717a8c51f8
08-31 22:16:46.304  5688  5688 F DEBUG   :                                      
08-31 22:16:46.304  5688  5688 F DEBUG   : backtrace:                           
08-31 22:16:46.304  5688  5688 F DEBUG   :       #00 pc 00000000001ff1f8  /data/app/com.celzero.bravedns-UxTeBgkEWVRkKM8ET5T-5w==/base.apk (offset 0x15c000) (runtime.raise+40)
08-31 22:16:46.341  3640  3640 D WidgetViewService: --------requestDataUsageUpdate mCurrentDataSim=0

```

**Comment by ignoramous** [comment]
Fixed: https://github.com/celzero/firestack/commit/09a1fd70f759d55b5408721be32fdc998d79a438
