### ISSUE TITLE
intra/dns53: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by hussainmohd-a** [celzero/firestack#53]
```
05-18 21:59:36.417 15856 15945 I GoLog   : mdns.go:123: I mdns: oquery: no response for 47901257-c37c-494d-9cca-e67ac36fc61d.local
05-18 21:59:36.417 15856 15945 I GoLog   : mdns.go:305: I mdns: closing client use4/6? true/false; oneshot? true; tracked 0; closed 1
05-18 21:59:36.417 15856 15942 E GoLog   : mdns.go:434: W mdns: listen: timeout for 47901257-c37c-494d-9cca-e67ac36fc61d.local.
05-18 21:59:36.417 15856 15942 E GoLog   : mdns.go:486: W mdns: recv: from(<nil>); closed; bytes(0), err(read udp4 0.0.0.0:40076: use of closed network connection)
05-18 21:59:36.421 15856     0 E Go      : panic: runtime error: invalid memory address or nil pointer dereference
05-18 21:59:36.421 15856     0 E Go      : [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x789132e8f0]
05-18 21:59:36.421 15856     0 E Go      : 
05-18 21:59:36.421 15856     0 E Go      : goroutine 895 [running]:
05-18 21:59:36.432 15856     0 E Go      : github.com/celzero/firestack/intra/dns53.clos(...)
05-18 21:59:36.433 15856     0 E Go      : 	/home/jitpack/build/intra/dns53/dot.go:149
05-18 21:59:36.433 15856     0 E Go      : github.com/celzero/firestack/intra/dns53.(*client).Close(0x40004e8140)
05-18 21:59:36.433 15856     0 E Go      : 	/home/jitpack/build/intra/dns53/mdns.go:308 +0x150
05-18 21:59:36.433 15856     0 E Go      : github.com/celzero/firestack/intra/dns53.clos(...)
05-18 21:59:36.433 15856     0 E Go      : 	/home/jitpack/build/intra/dns53/dot.go:149
05-18 21:59:36.433 15856     0 E Go      : github.com/celzero/firestack/intra/dns53.(*dnssd).oneshotQuery(0x400003c900, 0x40002a45a0)
05-18 21:59:36.433 15856     0 E Go      : 	/home/jitpack/build/intra/dns53/mdns.go:124 +0x96c
05-18 21:59:36.433 15856     0 E Go      : github.com/celzero/firestack/intra/dns53.(*dnssd).Query(0x400003c900, {0x7901e592c0?, 0x8?}, 0x40002a45a0, 0x40001509a0)
05-18 21:59:36.433 15856     0 E Go      : 	/home/jitpack/build/intra/dns53/mdns.go:144 +0x104
05-18 21:59:36.433 15856     0 E Go      : github.com/celzero/firestack/intra/dnsx.Req({0x789154e5a0?, 0x400003c900?}, {0x40003841b0?, 0x7890ed0168?}, 0x40004a1788?, 0x7890ef64f0?)
05-18 21:59:36.433 15856     0 E Go      : 	/home/jitpack/build/intra/dnsx/alg.go:1014 +0xbc
05-18 21:59:36.433 15856     0 E Go      : github.com/celzero/firestack/intra/dnsx.(*dnsgateway).q(0x40002a4000, {0x789154e5a0, 0x400003c900}, {0x0, 0x0}, {0x4000508030, 0x0, 0x1}, {0x40003841b0, 0x8}, ...)
05-18 21:59:36.433 15856     0 E Go      : 	/home/jitpack/build/intra/dnsx/alg.go:269 +0x1d4
05-18 21:59:36.433 15856     0 E Go      : github.com/celzero/firestack/intra/dnsx.(*resolver).forward(0x40002220b0, {0x4000174800, 0x3c, 0x800}, {0x0, 0x0, 0x0})
05-18 21:59:36.433 15856     0 E Go      : 	/home/jitpack/build/intra/dnsx/transport.go:390 +0xacc
05-18 21:59:36.433 15856     0 E Go      : github.com/celzero/firestack/intra/dnsx.(*resolver).dnsudp(0x78919589c0?, {0x4000174800?, 0x400012d860?, 0x4000336000?}, {0x790760a900, 0x4000239440})
05-18 21:59:36.433 15856     0 E Go      : 	/home/jitpack/build/intra/dnsx/transport.go:528 +0x38
05-18 21:59:36.435 15856     0 E Go      : github.com/celzero/firestack/intra/dnsx.(*resolver).reply.func2()
05-18 21:59:36.435 15856     0 E Go      : 	/home/jitpack/build/intra/dnsx/transport.go:568 +0x74
05-18 21:59:36.435 15856     0 E Go      : created by github.com/celzero/firestack/intra/dnsx.(*resolver).reply in goroutine 911
05-18 21:59:36.435 15856     0 E Go      : 	/home/jitpack/build/intra/dnsx/transport.go:578 +0x98
05-18 21:59:36.435 15856 15948 F libc    : Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 15948 (Thread-27), pid 15856 (elzero.bravedns)
```

**Comment by Rhys-T** [comment]
I just ran into what seems to be this same crash today. I can reliably reproduce it by asking Rethink[^version] to resolve any `*.local` (mDNS) domain name, e.g. through Firefox or AVNC, or Termux's `dig` command. (If you've already figured all this out, sorry for the noise - I couldn't tell from the commits above what the current status of this issue was.)

[^version]: 055j, because that's what F-Droid has so far.

It seems to happen whether or not any other machine returns an address for that domain name, but when it does get a response, it attempts to handle it before crashing. The other app never actually gets a response, though. (If the machine doesn't exist, Rethink doesn't crash until its outgoing query has timed out.)

<details><summary>Example crash when Rethink does get a response</summary>

```
05-26 12:46:51.018 11887 11971 I GoLog   : mdns.go:101: D mdns: oquery: ██████.local
05-26 12:46:51.018 11887 11971 I GoLog   : mdns.go:453: D mdns: send: sent query4 ██████.local.
05-26 12:46:51.018 11887 11971 I GoLog   : mdns.go:343: D mdns: query: waiting for ans to ██████
05-26 12:46:51.018 11887 11971 I GoLog   : mdns.go:112: D mdns: oquery: awaiting response ██████.local
05-26 12:46:51.021 11887 11958 D BatchLogger: signal sleep 2500 ms
05-26 12:46:51.043 11887 11921 I GoLog   : mdns.go:370: D mdns: listen: processing ██████.local ans for ██████.local.
05-26 12:46:51.044 11887 11921 I GoLog   : mdns.go:413: D mdns: listen: q: ██████.local.; sent ans &{%!s(*dns.Msg=&{{35278 true 0 true false false false false false false 0} false [{██████.local. 1 1}] [0x40001d21c0] [] []}) ██████.local.  ����  %!s(int=0) [] %!s(bool=true)}
05-26 12:46:51.044 11887 11921 I GoLog   : mdns.go:116: I mdns: oquery: q(██████.local) ans(██████.local.) 4(192.168.██.██) 6(<nil>)
05-26 12:46:51.044 11887 11921 I GoLog   : mdns.go:305: I mdns: closing client use4/6? true/false; oneshot? true; tracked 0; closed 1
05-26 12:46:51.045 11887 11921 E GoLog   : mdns.go:486: W mdns: recv: from(<nil>); closed; bytes(0), err(read udp4 0.0.0.0:36505: use of closed network connection)
05-26 12:46:51.045 11887 11921 I GoLog   : mdns.go:133: D mdns: err: <nil>; summary: type: DNS, id: mdns, latency: 0.000000, qname: , rdata: , rcode: 0, rttl: 0, server: 224.0.0.251:5353, relay: , status: 0, blocklists: 
05-26 12:46:51.047 11887     0 E Go      : panic: runtime error: invalid memory address or nil pointer dereference
05-26 12:46:51.048 11887     0 E Go      : [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6fccd3a8f0]
05-26 12:46:51.048 11887     0 E Go      : 
05-26 12:46:51.048 11887     0 E Go      : goroutine 247 [running]:
05-26 12:46:51.048 11887     0 E Go      : github.com/celzero/firestack/intra/dns53.clos(...)
05-26 12:46:51.048 11887     0 E Go      : 	/home/jitpack/build/intra/dns53/dot.go:149
05-26 12:46:51.048 11887     0 E Go      : github.com/celzero/firestack/intra/dns53.(*client).Close(0x4000210280)
05-26 12:46:51.048 11887     0 E Go      : 	/home/jitpack/build/intra/dns53/mdns.go:308 +0x150
05-26 12:46:51.048 11887     0 E Go      : github.com/celzero/firestack/intra/dns53.clos(...)
05-26 12:46:51.048 11887     0 E Go      : 	/home/jitpack/build/intra/dns53/dot.go:149
05-26 12:46:51.048 11887     0 E Go      : github.com/celzero/firestack/intra/dns53.(*dnssd).oneshotQuery(0x400003c380, 0x40002fa360)
05-26 12:46:51.048 11887     0 E Go      : 	/home/jitpack/build/intra/dns53/mdns.go:118 +0x828
05-26 12:46:51.048 11887     0 E Go      : github.com/celzero/firestack/intra/dns53.(*dnssd).Query(0x400003c380, {0x70e1f99168?, 0x8?}, 0x40002fa360, 0x400014ec60)
05-26 12:46:51.048 11887     0 E Go      : 	/home/jitpack/build/intra/dns53/mdns.go:144 +0x104
05-26 12:46:51.049 11887     0 E Go      : github.com/celzero/firestack/intra/dnsx.Req({0x6fccf5a5a0?, 0x400003c380?}, {0x40002ae6a8?, 0xd0?}, 0x4000270768?, 0x6fcc9b6ee8?)
05-26 12:46:51.049 11887     0 E Go      : 	/home/jitpack/build/intra/dnsx/alg.go:1014 +0xbc
05-26 12:46:51.049 11887     0 E Go      : github.com/celzero/firestack/intra/dnsx.(*dnsgateway).q(0x4000224000, {0x6fccf5a5a0, 0x400003c380}, {0x0, 0x0}, {0x4000422028, 0x0, 0x1}, {0x40002ae6a8, 0x8}, ...)
05-26 12:46:51.049 11887     0 E Go      : 	/home/jitpack/build/intra/dnsx/alg.go:269 +0x1d4
05-26 12:46:51.049 11887     0 E Go      : github.com/celzero/firestack/intra/dnsx.(*resolver).forward(0x40001bc0b0, {0x40000b5000, 0x33, 0x800}, {0x0, 0x0, 0x0})
05-26 12:46:51.049 11887     0 E Go      : 	/home/jitpack/build/intra/dnsx/transport.go:390 +0xacc
05-26 12:46:51.049 11887     0 E Go      : github.com/celzero/firestack/intra/dnsx.(*resolver).dnsudp(0x6fcd3649c0?, {0x40000b5000?, 0x400018e0c0?, 0x4000118060?}, {0x70d538cb18, 0x400018e540})
05-26 12:46:51.049 11887     0 E Go      : 	/home/jitpack/build/intra/dnsx/transport.go:528 +0x38
05-26 12:46:51.050 11887     0 E Go      : github.com/celzero/firestack/intra/dnsx.(*resolver).reply.func2()
05-26 12:46:51.050 11887     0 E Go      : 	/home/jitpack/build/intra/dnsx/transport.go:568 +0x74
05-26 12:46:51.050 11887     0 E Go      : created by github.com/celzero/firestack/intra/dnsx.(*resolver).reply in goroutine 246
05-26 12:46:51.050 11887     0 E Go      : 	/home/jitpack/build/intra/dnsx/transport.go:578 +0x98
--------- beginning of crash
05-26 12:46:51.052 11887 11924 F libc    : Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 11924 (Thread-22), pid 11887 (elzero.bravedns)
```

Note: the `����` on the `sent ans` line is actually the correct IPv4 address for the other machine, but output as _raw bytes_ instead of formatted into dotted-decimal.

</details>

It doesn't seem to matter what type of record I'm asking for - a `TXT` query will crash it just like an `A` query does.

Setting the app to `exclude` will of course keep it from crashing Rethink. (Termux `dig` still doesn't get an answer, but that's because it's directly speaking normal non-multicast DNS instead of using Android's resolver, and obviously it won't get an answer for `*.local` that way. Other apps resolve it just fine at that point.)

Reverse DNS lookups for 192.168.x.y don't trigger the crash, but they also don't get a response, so that might be a separate problem where `*.168.192.in-addr.arpa` isn't getting handled via mDNS. I can open that as another issue if you want. I don't know of anything that actually needs to do that sort of lookup, though, so it's not anything I desperately need fixed - I was just trying to think of other mDNS domains to test _this_ issue with, and happened to run across that.

**Comment by ignoramous** [comment]
`v055l` has the fix; specifically, this line: 
https://github.com/celzero/firestack/blob/76cc6ed0af72feb900164419ce891687f2a292ea/intra/dns53/mdns.go#L307

versus (has `nil` ptr bug):
https://github.com/celzero/firestack/blob/ca2ca3d917b50c898f566c3b25d987b4829a4491/intra/dns53/mdns.go#L307-L310

https://github.com/celzero/firestack/blob/ca2ca3d917b50c898f566c3b25d987b4829a4491/intra/dns53/dot.go#L147-L151

The problem was, underlying *type* (typically a `struct` or a pointer to `struct`; in this case ptrs, `c.unicast[4|6]` & `c.multicast[4|6]`) of a *non-nil* `interface` (in this case, `io.Closer`) can be `nil` in Go (that is `c io.Closer` in `dns53.dot.go:clos` is *not* nil, but `c.Close()` may yet panic with `nil` ptr). There are many a blog posts about this ([ex](https://www.jerf.org/iri/post/2957/)/[mirror](https://archive.ph/puqCb)) since it trips many a developer familiar with c/cpp semantics for `null` (like it tripped me).

**Comment by Rhys-T** [comment]
Rethink v055l just showed up on F-Droid today, and this seems to be working now. Thanks!
