### ISSUE TITLE
runtime error: index out of range

### ISSUE THREAD

**Issue by hussainmohd-a** [celzero/firestack#59]
```
05-30 13:58:27.673  7237  7265 I GoLog   : tun2socks.go:77: I tun: new log-level 1; debug? true
05-30 13:58:27.677  7237     0 E Go      : panic: runtime error: index out of range [-2]
05-30 13:58:27.677  7237     0 E Go      : 
05-30 13:58:27.677  7237     0 E Go      : goroutine 72 [running]:
05-30 13:58:27.678  7237     0 E Go      : github.com/celzero/firestack/intra/netstack.(*supervisor).queuePacket(0x4f9d0240, 0x4fa34008, 0x0)
05-30 13:58:27.678  7237     0 E Go      : 	/home/jitpack/build/intra/netstack/forwarders.go:271 +0x584
05-30 13:58:27.678  7237     0 E Go      : github.com/celzero/firestack/intra/netstack.(*readVDispatcher).dispatch(0x4f9d0270)
05-30 13:58:27.678  7237     0 E Go      : 	/home/jitpack/build/intra/netstack/dispatchers.go:253 +0x544
05-30 13:58:27.678  7237     0 E Go      : github.com/celzero/firestack/intra/netstack.(*endpoint).dispatchLoop(0x4f9be0c0, {0x83ebfcb0, 0x4f9d0270})
05-30 13:58:27.678  7237     0 E Go      : 	/home/jitpack/build/intra/netstack/fdbased.go:461 +0x304
05-30 13:58:27.678  7237     0 E Go      : created by github.com/celzero/firestack/intra/netstack.(*endpoint).Attach in goroutine 18
05-30 13:58:27.678  7237     0 E Go      : 	/home/jitpack/build/intra/netstack/fdbased.go:305 +0x288
05-30 13:58:27.679  7237  7270 F libc    : Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 7270 (Thread-14), pid 7237 (elzero.bravedns)
```

**Comment by hussainmohd-a** [comment]
more logs
```
05-30 13:58:19.617  7021     0 E Go      : panic: runtime error: index out of range [-4]
05-30 13:58:19.617  7021     0 E Go      : 
05-30 13:58:19.618  7021     0 E Go      : goroutine 34 [running]:
05-30 13:58:19.618  7021     0 E Go      : github.com/celzero/firestack/intra/netstack.(*supervisor).queuePacket(0x4f936240, 0x4fa2c008, 0x0)
05-30 13:58:19.618  7021     0 E Go      : 	/home/jitpack/build/intra/netstack/forwarders.go:271 +0x584
05-30 13:58:19.618  7021     0 E Go      : github.com/celzero/firestack/intra/netstack.(*readVDispatcher).dispatch(0x4f936270)
05-30 13:58:19.618  7021     0 E Go      : 	/home/jitpack/build/intra/netstack/dispatchers.go:253 +0x544
05-30 13:58:19.618  7021     0 E Go      : github.com/celzero/firestack/intra/netstack.(*endpoint).dispatchLoop(0x4f9340c0, {0x83dfacb0, 0x4f936270})
05-30 13:58:19.618  7021     0 E Go      : 	/home/jitpack/build/intra/netstack/fdbased.go:461 +0x304
05-30 13:58:19.618  7021     0 E Go      : created by github.com/celzero/firestack/intra/netstack.(*endpoint).Attach in goroutine 18
05-30 13:58:19.618  7021     0 E Go      : 	/home/jitpack/build/intra/netstack/fdbased.go:305 +0x288
05-30 13:58:19.619  7021  7053 F libc    : Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 7053 (Thread-17), pid 7021 (elzero.bravedns)
```

**Comment by ignoramous** [comment]
`uint32` to `int` conversion overflow on 32-bit platforms.

```diff
05-30 13:55:14.521  4652  4708 F libc    : Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 4708 (Thread-16), pid 4652 (elzero.bravedns)
05-30 13:55:15.601  4818  4818 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
05-30 13:55:15.601  4818  4818 F DEBUG   : Native Crash TIME: 223934
05-30 13:55:15.601  4818  4818 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
+ 05-30 13:55:15.601  4818  4818 F DEBUG   : Build fingerprint: 'Itel/SA332Q/itel-A16-Plus:10/QP1A.190711.020/OP-V027-...:user/release-keys'
05-30 13:55:15.602  4818  4818 F DEBUG   : Revision: '0'
+ 05-30 13:55:15.602  4818  4818 F DEBUG   : ABI: 'arm'
05-30 13:55:15.682  4818  4818 F DEBUG   : Timestamp: 2024-05-30 13:55:15+0800
05-30 13:55:15.682  4818  4818 F DEBUG   : pid: 4652, tid: 4708, name: Thread-16  >>> com.celzero.bravedns <<<
05-30 13:55:15.682  4818  4818 F DEBUG   : uid: 10146
05-30 13:55:15.682  4818  4818 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
05-30 13:55:15.682  4818  4818 F DEBUG   :     r0  00000000  r1  00001264  r2  00000006  r3  00000008
05-30 13:55:15.682  4818  4818 F DEBUG   :     r4  0000122c  r5  8157d000  r6  00000000  r7  0000010c
05-30 13:55:15.682  4818  4818 F DEBUG   :     r8  00000007  r9  00000000  r10 4f886b48  r11 820b2431
05-30 13:55:15.682  4818  4818 F DEBUG   :     ip  820edd5d  sp  4f84ede8  lr  815ed514  pc  8160f3dc
05-30 13:55:15.700  4818  4818 F DEBUG   : 
05-30 13:55:15.700  4818  4818 F DEBUG   : backtrace:
05-30 13:55:15.703  4818  4818 F DEBUG   :       #00 pc 0020b3dc  /data/app/com.celzero.bravedns-YqKLIjxXqd_6aWGPdKrjdw==/base.apk (offset 0x10cc000)
```
