### ISSUE TITLE
tcp.Complete: Completing already completed

### ISSUE THREAD

**Issue by hussainmohd-a** [celzero/firestack#69]
```
F tcp.Proxy [11] Completing already completed forwarder request
 (#1)


goroutine 1322 [running]:
github.com/celzero/firestack/intra/log.(*simpleLogger).Stack(0x40001600e0, 0x0, {0x4008c48480?, 0x4008c483c0?}, {0x4008f94000, 0x10000, 0x10000})
	/home/jitpack/build/intra/log/logger.go:400 +0x2c0
github.com/celzero/firestack/intra/log.C({0x4008c483c0, 0x3e}, {0x4008f94000, 0x10000, 0x10000})
	/home/jitpack/build/intra/log/log.go:136 +0xf8
github.com/celzero/firestack/intra/core.trace(0x40001600e0?, {0x4008c483c0, 0x3e})
	/home/jitpack/build/intra/core/dontpanic.go:101 +0x1a4
github.com/celzero/firestack/intra/core.Recover(0xb, {0x79f6bc1cb8, 0x9})
	/home/jitpack/build/intra/core/dontpanic.go:74 +0x13c
panic({0x79f72b23c0?, 0x79f73bd030?})
	/home/jitpack/golang/go/src/runtime/panic.go:770 +0x124
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*ForwarderRequest).Complete(0x40003a8180, 0x1)
	/tmp/gomobile-work-1472328549/pkg/mod/gvisor.dev/gvisor@v0.0.0-20240524213522-f2b01a6e47ff/pkg/tcpip/transport/tcp/forwarder.go:130 +0x240
github.com/celzero/firestack/intra/netstack.(*GTCPConn).makeEndpoint(0x40001819e0, 0x10?)
	/home/jitpack/build/intra/netstack/tcp.go:135 +0x58
github.com/celzero/firestack/intra/netstack.(*GTCPConn).Connect(...)
	/home/jitpack/build/intra/netstack/tcp.go:121
github.com/celzero/firestack/intra.(*tcpHandler).Proxy(0x400016e880, 0x40001819e0, {{{0x0, 0xffff0a6fde01}, 0x4000126000}, 0xb722}, {{{0x0, 0xffff9df0fb3d}, 0x4000126000}, 0x50})
	/home/jitpack/build/intra/tcp.go:240 +0x760
github.com/celzero/firestack/intra.(*tcpHandler).Error(0x4007daff98?, 0x79f7095d74?, {{{0x0, 0xffff0a6fde01}, 0x4000126000}, 0xb722}, {{{0x0, 0xffff9df0fb3d}, 0x4000126000}, 0x50}, ...)
	/home/jitpack/build/intra/tcp.go:174 +0x44
created by github.com/celzero/firestack/intra/netstack.setupTcpHandler.tcpForwarder.func1 in goroutine 1130
	/home/jitpack/build/intra/netstack/tcp.go:77 +0x388
```

**Comment by ignoramous** [comment]
https://github.com/celzero/firestack/issues/69
