### ISSUE TITLE
panic: sync/atomic: swap of inconsistently typed value into Value

### ISSUE THREAD

**Issue by hussainmohd-a** [celzero/firestack#70]
panic: sync/atomic: swap of inconsistently typed value into Value

```

goroutine 494 [running, locked to thread]:
sync/atomic.(*Value).Swap(0x400012e420, {0x71917b6060, 0x40001381d8})
	/home/jitpack/golang/go/src/sync/atomic/value.go:122 +0x100
github.com/celzero/firestack/intra/core.(*Volatile[...]).Swap(0x71917dacc0, {0x71917cce98, 0x40001381d8})
	/home/jitpack/build/intra/core/volatile.go:81 +0x100
github.com/celzero/firestack/tunnel.(*pcapsink).file(0x400013c180, {0x71917cce98?, 0x40001381d8?})
	/home/jitpack/build/tunnel/tunnel.go:158 +0x9c
github.com/celzero/firestack/tunnel.(*gtunnel).SetPcap(0x3a?, {0x400030c340, 0x3a})
	/home/jitpack/build/tunnel/tunnel.go:310 +0x29c
main.proxyintra_Tunnel_SetPcap(0x96000?, {0x711b65f100, 0x3a, {0x0, 0x0, 0x0, 0x0}})
	/tmp/gomobile-work-3772484414/src/gobind/go_intramain.go:1015 +0xa8

```

**Comment by hussainmohd-a** [comment]
[panic_pcap.txt](https://github.com/user-attachments/files/16041590/panic_pcap.txt)
