### ISSUE TITLE
retrier#CloseRead/CloseWrite: nil pointer dereference

### ISSUE THREAD

**Issue by hussainmohd-a** [celzero/firestack#83]
_CloseRead_

```js
E retrier: read: [192.168.0.101:38450<-76.223.92.165:443] 0; err: read tcp 192.168.0.101:38450->76.223.92.165:443: read: software caused connection abort
D control: netbinder: Exit: tcp4(76.223.92.165:443); err? <nil>
E retrier: read: [192.168.0.101:42752<-104.244.42.130:443] 0; err: read tcp 192.168.0.101:42752->104.244.42.130:443: read: software caused connection abort
E retrier: read: [192.168.0.101:39142<-163.70.138.1:443] 0; err: read tcp 192.168.0.101:39142->163.70.138.1:443: read: software caused connection abort
D intra: e2072f3c4d15648a download(4474) done(read tcp 192.168.0.101:42752->104.244.42.130:443: read: software caused connection abort) b/w a(10.111.222.1:40502->104.244.42.2:443) => b(192.168.0.101:42752<-104.244.42.130:443)
E retrier: read: [192.168.0.101:40076<-216.239.32.223:443] 0; err: read tcp 192.168.0.101:40076->216.239.32.223:443: read: software caused connection abort
D intra: d0ac7e1395f33267 download(2856) done(read tcp 192.168.0.101:39142->163.70.138.1:443: read: software caused connection abort) b/w a(10.111.222.1:38426->157.240.192.4:443) => b(192.168.0.101:39142<-163.70.138.1:443)
D intra: 758f4d2af814a140 download(1756) done(read tcp 192.168.0.101:40076->216.239.32.223:443: read: software caused connection abort) b/w a(10.111.222.1:46618->216.239.34.223:443) => b(192.168.0.101:40076<-216.239.32.223:443)
E retrier: read: [192.168.0.101:43972<-142.250.182.74:443] 0; err: read tcp 192.168.0.101:43972->142.250.182.74:443: read: software caused connection abort
D intra: a782c79327bbe752 download(6286) done(read tcp 192.168.0.101:43972->142.250.182.74:443: read: software caused connection abort) b/w a([fd66:f83a:c650::1]:47346->[2404:6800:4007:811::200a]:443) => b(192.168.0.101:43972<-142.250.182.74:443)
VV ns: tun(173): WritePackets (to tun): written(1)/total(1)
VV ns: tun(173): WritePackets (to tun): written(1)/total(1)
E retrier: read: [192.168.0.101:49728<-91.108.56.106:443] 0; err: read tcp 192.168.0.101:49728->91.108.56.106:443: read: software caused connection abort
D intra: f4f0a9aeb9245aed download(178) done(read tcp 192.168.0.101:49728->91.108.56.106:443: read: software caused connection abort) b/w a(10.111.222.1:46786->91.108.56.106:443) => b(192.168.0.101:49728<-91.108.56.106:443)
VV ns: tun(173): WritePackets (to tun): written(1)/total(1)
VV ns: tun(173): WritePackets (to tun): written(1)/total(1)
VV ns: tun(173): WritePackets (to tun): written(1)/total(1)
E retrier: read: [192.168.0.101:39128<-163.70.138.1:443] 0; err: read tcp 192.168.0.101:39128->163.70.138.1:443: read: software caused connection abort
D intra: 30eec0bf9ff6f0fd download(3303) done(read tcp 192.168.0.101:39128->163.70.138.1:443: read: software caused connection abort) b/w a(10.111.222.1:38416->157.240.192.4:443) => b(192.168.0.101:39128<-163.70.138.1:443)
E retrier: read: [192.168.0.101:40824<-99.83.222.213:443] 0; err: read tcp 192.168.0.101:40824->99.83.222.213:443: read: software caused connection abort
E retrier: read: [192.168.0.101:48198<-142.250.196.42:443] 0; err: read tcp 192.168.0.101:48198->142.250.196.42:443: read: software caused connection abort
D intra: 23676b124d45034d download(6920) done(read tcp 192.168.0.101:40824->99.83.222.213:443: read: software caused connection abort) b/w a(10.111.222.1:42304->75.2.97.213:443) => b(192.168.0.101:40824<-99.83.222.213:443)
D intra: 4f2fe922cd863eac download(9792) done(read tcp 192.168.0.101:48198->142.250.196.42:443: read: software caused connection abort) b/w a([fd66:f83a:c650::1]:46054->[2404:6800:4007:815::200a]:443) => b(192.168.0.101:48198<-142.250.196.42:443)
VV ns: tun(173): WritePackets (to tun): written(1)/total(1)
VV ns: tun(173): WritePackets (to tun): written(1)/total(1)
VV ns: tun(173): WritePackets (to tun): written(1)/total(1)
VV ns: tun(173): dispatch: got(76 bytes), err(errno 0)
VV ns: tun(173): forwarder: q on proc 2, 2048 | :38416 => :443
VV ns: tun(173): dispatch: done? false
VV ns: tun(173): inject-inbound (from tun) 2048
VV ns: tun(173): WritePackets (to tun): written(1)/total(1)
E retrier: readfrom: done; sz: 6905; err: readfrom tcp 192.168.0.101:39128->163.70.138.1:443: write tcp 192.168.0.101:39128->163.70.138.1:443: write: broken pipe
D intra: 30eec0bf9ff6f0fd upload(6905) done(readfrom tcp 192.168.0.101:39128->163.70.138.1:443: write tcp 192.168.0.101:39128->163.70.138.1:443: write: broken pipe) b/w a(10.111.222.1:38416->157.240.192.4:443) => b(192.168.0.101:39128<-163.70.138.1:443)
VV intra: queueSummary: over 40002e2310 40001823f0 30eec0bf9ff6f0fd
VV ns: tun(173): WritePackets (to tun): written(1)/total(1)
D connmap: untrack: 2 conns for 30eec0bf9ff6f0fd
VV intra: end? sendNotif: socket-summary: id=30eec0bf9ff6f0fd pid=Exit uid=10268 down=3303 up=6905 dur=132 synack=52 msg=read tcp 192.168.0.101:39128->163.70.138.1:443: read: software caused connection abort
readfrom tcp 192.168.0.101:39128->163.70.138.1:443: write tcp 192.168.0.101:39128->163.70.138.1:443: write: broken pipe
E retrier: dial(SplitTCP,RetryAfterSplit) none->76.223.92.165:443; strat: 1, split? false, rtt: 6ms; err? dial tcp 76.223.92.165:443: connect: network is unreachable
E retrier: read# 1: [none<-76.223.92.165:443] 0; err? dial tcp 76.223.92.165:443: connect: network is unreachable
D control: netbinder: Exit: tcp4(76.223.92.165:443); err? <nil>
17 August 2024, 08:05:36: F tcp.forward:3ddc614e9ddaced5 [0] runtime error: invalid memory address or nil pointer dereference
 (#1)
17 August 2024, 08:05:36: goroutine 82183 [running]:
github.com/celzero/firestack/intra/log.(*simpleLogger).Stack(0x40001e0230, 0x0, {0x400022a540?, 0x400022a380?}, {0x400991c000, 0x10000, 0x10000})
	/home/jitpack/build/intra/log/logger.go:400 +0x2c0
github.com/celzero/firestack/intra/log.C({0x400022a380, 0x62}, {0x400991c000, 0x10000, 0x10000})
	/home/jitpack/build/intra/log/log.go:136 +0xf8
github.com/celzero/firestack/intra/core.trace(0x40001e0230?, {0x400022a380, 0x62})
	/home/jitpack/build/intra/core/dontpanic.go:101 +0x198
github.com/celzero/firestack/intra/core.Recover(0x0, {0x4008986500, 0x1c})
	/home/jitpack/build/intra/core/dontpanic.go:74 +0x13c
panic({0x70a0935100?, 0x70a0e85790?})
	/home/jitpack/golang/go/src/runtime/panic.go:785 +0x124
net.(*TCPConn).CloseRead(0x40080b1978?)
	/home/jitpack/golang/go/src/net/tcpsock.go:187 +0x18
github.com/celzero/firestack/intra/dialers.(*retrier).CloseRead(0x70a0a2ada8?)
	/home/jitpack/build/intra/dialers/retrier.go:266 +0xd0
github.com/celzero/firestack/intra/dialers.(*retrier).Close(0x4008842d20)
	/home/jitpack/build/intra/dialers/retrier.go:409 +0x24
github.com/celzero/firestack/intra/core.(*cm).Untrack(0x40000c8150, {0x400033f110, 0x10})
	/home/jitpack/build/intra/core/connmap.go:138 +0x108
panic({0x70a0935100?, 0x70a0e85790?})
	/home/jitpack/golang/go/src/runtime/panic.go:785 +0x124
net.(*TCPConn).SetReadDeadline(0x70a01e3ddc?, {0x0?, 0x40088409b0?, 0x0?})
	<autogenerated>:1 +0x24
github.com/celzero/firestack/intra/dialers.(*retrier).Read(0x4008842d20, {0x4009660000, 0x10000, 0x10000})
	/home/jitpack/build/intra/dialers/retrier.go:294 +0x56c
io.copyBuffer({0x7442fa2c58, 0x40002b5490}, {0x74544626b8, 0x4008842d20}, {0x4009660000, 0x10000, 0x10000})
	/home/jitpack/golang/go/src/io/io.go:429 +0x18c
io.CopyBuffer({0x7442fa2c58?, 0x40002b5490?}, {0x74544626b8?, 0x4008842d20?}, {0x4009660000?, 0x70a0a207e0?, 0x70a0a207e0?})
	/home/jitpack/golang/go/src/io/io.go:402 +0x38
github.com/celzero/firestack/intra/core.Pipe({0x7442fa2c58, 0x40002b5490}, {0x74544626b8, 0x4008842d20})
	/home/jitpack/build/intra/core/cp.go:36 +0x1cc
github.com/celzero/firestack/intra.download({0x400033f110, 0x10}, {0x70a0a2ae00, 0x40002b5490}, {0x70a0a2d038, 0x4008842d20})
	/home/jitpack/build/intra/common.go:50 +0xac
github.com/celzero/firestack/intra.forward({0x70a0a2ae00, 0x40002b5490}, {0x70a0a2d038, 0x4008842d20}, 0x40002e2310, 0x40001823f0, 0x4008842c80)
	/home/jitpack/build/intra/common.go:66 +0x100
github.com/celzero/firestack/intra.(*tcpHandler).handle.func1()
	/home/jitpack/build/intra/tcp.go:311 +0x84
github.com/celzero/firestack/intra/core.Go.func1()
	/home/jitpack/build/intra/core/async.go:14 +0x5c
created by github.com/celzero/firestack/intra/core.Go in goroutine 82127
	/home/jitpack/build/intra/core/async.go:11 +0x7c
```

**Comment by hussainmohd-a** [comment]
crash log for _CloseWrite_

```js
E retrier: dial(SplitTCP,RetryAfterSplit) none->163.70.138.1:443; strat: 1, split? true, rtt: 0ms; err? dial tcp 163.70.138.1:443: connect: network is unreachable
D rdial: commondial: confirmed ip 163.70.138.1 for 163.70.138.1:443 failed with err dial tcp 163.70.138.1:443: connect: network is unreachable
D rdial: duration: 1.162396ms; failed 163.70.138.1:443; confirmed? 163.70.138.1, sz: 1
I proxy: exit: dial(tcp) to 163.70.138.1:443; err? dial tcp 163.70.138.1:443: connect: network is unreachable
W tcp: err dialing 01f116f64bc7b9c3 proxy(Exit) to dst(163.70.138.1:443) for 10268: dial tcp 163.70.138.1:443: connect: network is unreachable
W tcp: dial: #2: 01f116f64bc7b9c3 failed; addr(163.70.138.1:443); for uid 10268 (6); w err(dial tcp 163.70.138.1:443: connect: network is unreachable)
D rdial: commondial: dialing (host:port) [2a03:2880:f09d:0:face:b00c:0:6206]:443
D ipmap: Get: 2a03:2880:f09d:0:face:b00c:0:6206 => []
V rdial: commondial: dialing confirmed ip 2a03:2880:f09d:0:face:b00c:0:6206 for [2a03:2880:f09d:0:face:b00c:0:6206]:443
D control: netbinder: Exit: tcp6([2a03:2880:f09d:0:face:b00c:0:6206]:443); err? <nil>
17 August 2024, 08:05:36: F c.upload: 3ddc614e9ddaced5 [11] runtime error: invalid memory address or nil pointer dereference
 (#1)
17 August 2024, 08:05:36: goroutine 82184 [running]:
github.com/celzero/firestack/intra/log.(*simpleLogger).Stack(0x40001e0230, 0x0, {0x400a504700?, 0x63?}, {0x400991c000, 0x10000, 0x10000})
	/home/jitpack/build/intra/log/logger.go:400 +0x2c0
github.com/celzero/firestack/intra/log.C({0x400022a690, 0x61}, {0x400991c000, 0x10000, 0x10000})
	/home/jitpack/build/intra/log/log.go:136 +0xf8
github.com/celzero/firestack/intra/core.trace(0x40001e0230?, {0x400022a690, 0x61})
	/home/jitpack/build/intra/core/dontpanic.go:101 +0x198
github.com/celzero/firestack/intra/core.Recover(0xb, {0x40089865a0, 0x1a})
	/home/jitpack/build/intra/core/dontpanic.go:74 +0x13c
panic({0x70a0935100?, 0x70a0e85790?})
	/home/jitpack/golang/go/src/runtime/panic.go:785 +0x124
net.(*TCPConn).CloseWrite(0x40081ace38?)
	/home/jitpack/golang/go/src/net/tcpsock.go:199 +0x18
github.com/celzero/firestack/intra/dialers.(*retrier).CloseWrite(0x70a09e4de0?)
	/home/jitpack/build/intra/dialers/retrier.go:403 +0xd0
github.com/celzero/firestack/intra/core.CloseTCPWrite({0x7454462650, 0x4008842d20})
	/home/jitpack/build/intra/core/closer.go:88 +0xc0
github.com/celzero/firestack/intra/core.CloseOp({0x7442fb0818, 0x4008842d20}, 0x1)
	/home/jitpack/build/intra/core/closer.go:142 +0x394
github.com/celzero/firestack/intra.upload({0x400033f110, 0x10}, {0x70a0a2ae00, 0x40002b5490}, {0x70a0a2d038, 0x4008842d20}, 0x4008063490)
	/home/jitpack/build/intra/common.go:43 +0x2e4
created by github.com/celzero/firestack/intra.forward in goroutine 82183
	/home/jitpack/build/intra/common.go:65 +0xe4

```
