### ISSUE TITLE
Nil ptr at doh.AddEdnsPadding L66

### ISSUE THREAD

**Issue by ignoramous** [celzero/firestack#96]
L66:
```
18 September 2024, 08:56:12: F alg.qs.clients4.google.com. [11] runtime error: invalid memory address or nil pointer dereference
 (#1)
18 September 2024, 08:56:12: goroutine 40513 [running]:
...
	/home/jitpack/golang/go/src/runtime/panic.go:785 +0x124
github.com/celzero/firestack/intra/doh.AddEdnsPadding(0x4008fd4cf0)
	/home/jitpack/build/intra/doh/padding.go:66 +0x70
github.com/celzero/firestack/intra/doh.(*transport).doDoh(0x400035c300, {0x40098a0364, 0x4}, 0x4008fd4cf0)
	/home/jitpack/build/intra/doh/doh.go:343 +0x44
github.com/celzero/firestack/intra/doh.(*transport).Query(0x400035c300, {0x40098a0360, 0x8}, 0x4008fd4cf0, 0x40002e2900)
	/home/jitpack/build/intra/doh/doh.go:605 +0xa8
github.com/celzero/firestack/intra/dnsx.Req({0x7de5aa9d60, 0x400035c300}, {0x40098a0360, 0x8}, 0x4008fd4cf0, 0x40002e2900)
	/home/jitpack/build/intra/dnsx/alg.go:1101 +0xd8
github.com/celzero/firestack/intra/dnsx.(*dnsgateway).querySecondary(0x4000162120, {0x7de5aa9d60, 0x400035c300}, {0x40098a0360, 0x8}, 0x4008fd4cf0, 0x400978a460)
	/home/jitpack/build/intra/dnsx/alg.go:225 +0x1cc
github.com/celzero/firestack/intra/dnsx.(*dnsgateway).qs.func1.1()
	/home/jitpack/build/intra/dnsx/alg.go:184 +0x38
github.com/celzero/firestack/intra/core.Grx[...].func1()
	/home/jitpack/build/intra/core/async.go:75 +0x8c
created by github.com/celzero/firestack/intra/core.Grx[...] in goroutine 40404
	/home/jitpack/build/intra/core/async.go:71 +0xfc
```

L76
```
19 September 2024, 03:30:22: F alg.qs.api.github.com. [11] runtime error: invalid memory address or nil pointer dereference
 (#1)
19 September 2024, 03:30:22: goroutine 185155 [running]:
...
panic({0x7de3db1e00?, 0x7de4317ec0?})
	/home/jitpack/golang/go/src/runtime/panic.go:785 +0x124
github.com/celzero/firestack/intra/doh.AddEdnsPadding(0x400985ec60)
	/home/jitpack/build/intra/doh/padding.go:76 +0x354
github.com/celzero/firestack/intra/doh.(*transport).doDoh(0x4007efc000, {0x400969f1a4, 0x4}, 0x400985ec60)
	/home/jitpack/build/intra/doh/doh.go:343 +0x44
github.com/celzero/firestack/intra/doh.(*transport).Query(0x4007efc000, {0x400969f1a0, 0x8}, 0x400985ec60, 0x40098e0e40)
	/home/jitpack/build/intra/doh/doh.go:605 +0xa8
github.com/celzero/firestack/intra/dnsx.Req({0x7de3ea9d60, 0x4007efc000}, {0x400969f1a0, 0x8}, 0x400985ec60, 0x40098e0e40)
	/home/jitpack/build/intra/dnsx/alg.go:1101 +0xd8
github.com/celzero/firestack/intra/dnsx.(*dnsgateway).querySecondary(0x40000ae120, {0x7de3ea9d60, 0x4007efc000}, {0x400969f1a0, 0x8}, 0x400985ec60, 0x400027d730)
	/home/jitpack/build/intra/dnsx/alg.go:225 +0x1cc
github.com/celzero/firestack/intra/dnsx.(*dnsgateway).qs.func1.1()
	/home/jitpack/build/intra/dnsx/alg.go:184 +0x38
github.com/celzero/firestack/intra/core.Grx[...].func1()
	/home/jitpack/build/intra/core/async.go:75 +0x8c
created by github.com/celzero/firestack/intra/core.Grx[...] in goroutine 185140
	/home/jitpack/build/intra/core/async.go:71 +0xfc
```

L67

```
21 September 2024, 13:18:21: F alg.qs.time.android.com. [11] runtime error: invalid memory address or nil pointer dereference
 (#1)
21 September 2024, 13:18:21: goroutine 105699 [running]:
github.com/celzero/firestack/intra/log.(*simpleLogger).Stack(0x40001562a0, 0x0, {0x400998f110?, 0x400038d080?}, {0x400a5a2000, 0x80000, 0x80000})
	/home/jitpack/build/intra/log/logger.go:398 +0x2c8
github.com/celzero/firestack/intra/log.C({0x400038d080, 0x5f}, {0x400a5a2000, 0x80000, 0x80000})
	/home/jitpack/build/intra/log/log.go:137 +0xf8
github.com/celzero/firestack/intra/core.trace(0x40001562a0?, {0x400038d080, 0x5f})
	/home/jitpack/build/intra/core/dontpanic.go:101 +0x19c
github.com/celzero/firestack/intra/core.Recover(0xb, {0x4008e28a80, 0x18})
	/home/jitpack/build/intra/core/dontpanic.go:74 +0x13c
panic({0x7de6db1940?, 0x7de7317c20?})
	/home/jitpack/golang/go/src/runtime/panic.go:785 +0x124
github.com/celzero/firestack/intra/doh.AddEdnsPadding(0x4009b075f0)
	/home/jitpack/build/intra/doh/padding.go:67 +0x70
github.com/celzero/firestack/intra/doh.(*transport).doDoh(0x4008668600, {0x40087d3884, 0x4}, 0x4009b075f0)
	/home/jitpack/build/intra/doh/doh.go:343 +0x44
github.com/celzero/firestack/intra/doh.(*transport).Query(0x4008668600, {0x40087d3880, 0x8}, 0x4009b075f0, 0x40095512c0)
	/home/jitpack/build/intra/doh/doh.go:605 +0xa8
github.com/celzero/firestack/intra/dnsx.Req({0x7de6ea98e0, 0x4008668600}, {0x40087d3880, 0x8}, 0x4009b075f0, 0x40095512c0)
	/home/jitpack/build/intra/dnsx/alg.go:1101 +0xd8
github.com/celzero/firestack/intra/dnsx.(*dnsgateway).querySecondary(0x40001b6120, {0x7de6ea98e0, 0x4008668600}, {0x40087d3880, 0x8}, 0x4009b075f0, 0x40089c5ce0)
	/home/jitpack/build/intra/dnsx/alg.go:225 +0x1cc
github.com/celzero/firestack/intra/dnsx.(*dnsgateway).qs.func1.1()
	/home/jitpack/build/intra/dnsx/alg.go:184 +0x38
github.com/celzero/firestack/intra/core.Grx[...].func1()
	/home/jitpack/build/intra/core/async.go:76 +0x8c
created by github.com/celzero/firestack/intra/core.Grx[...] in goroutine 105697
	/home/jitpack/build/intra/core/async.go:72 +0xfc
```

**Comment by ignoramous** [comment]
Also: #76

**Comment by ignoramous** [comment]
L119

```
21 September 2024, 22:08:40: F alg.qs.45.127.108.190.in.tot1.0.pixel.archive.vn. [11] runtime error: invalid memory address or nil pointer dereference
 (#1)
21 September 2024, 22:08:40: goroutine 11084 [running]:
github.com/celzero/firestack/intra/log.(*simpleLogger).Stack(0x40001661c0, 0x0, {0x4000259600?, 0x4000259480?}, {0x4009ea4000, 0x80000, 0x80000})
	/home/jitpack/build/intra/log/logger.go:398 +0x2c8
github.com/celzero/firestack/intra/log.C({0x4000259480, 0x78}, {0x4009ea4000, 0x80000, 0x80000})
	/home/jitpack/build/intra/log/log.go:137 +0xf8
github.com/celzero/firestack/intra/core.trace(0x40001661c0?, {0x4000259480, 0x78})
	/home/jitpack/build/intra/core/dontpanic.go:101 +0x19c
github.com/celzero/firestack/intra/core.Recover(0xb, {0x40091b26c0, 0x31})
	/home/jitpack/build/intra/core/dontpanic.go:74 +0x13c
panic({0x7de49f1b80?, 0x7de4f57ee0?})
	/home/jitpack/golang/go/src/runtime/panic.go:785 +0x124
github.com/celzero/firestack/intra/doh.padQuery(0x4009b30b40)
	/home/jitpack/build/intra/doh/padding.go:119 +0x228
github.com/celzero/firestack/intra/doh.(*transport).doDoh(0x400862eb00, {0x40098e798c, 0x4}, 0x4009b30b40)
	/home/jitpack/build/intra/doh/doh.go:343 +0x44
github.com/celzero/firestack/intra/doh.(*transport).Query(0x400862eb00, {0x40098e7988, 0x8}, 0x4009b30b40, 0x4009be9380)
	/home/jitpack/build/intra/doh/doh.go:609 +0xa8
github.com/celzero/firestack/intra/dnsx.Req({0x7de4ae9b20, 0x400862eb00}, {0x40098e7988, 0x8}, 0x4009b30b40, 0x4009be9380)
	/home/jitpack/build/intra/dnsx/alg.go:1101 +0xd8
github.com/celzero/firestack/intra/dnsx.(*dnsgateway).querySecondary(0x400021e120, {0x7de4ae9b20, 0x400862eb00}, {0x40098e7988, 0x8}, 0x4009b30b40, 0x40088a6c40)
	/home/jitpack/build/intra/dnsx/alg.go:225 +0x1cc
github.com/celzero/firestack/intra/dnsx.(*dnsgateway).qs.func1.1()
	/home/jitpack/build/intra/dnsx/alg.go:184 +0x38
github.com/celzero/firestack/intra/core.Grx[...].func1()
	/home/jitpack/build/intra/core/async.go:76 +0x8c
created by github.com/celzero/firestack/intra/core.Grx[...] in goroutine 11083
	/home/jitpack/build/intra/core/async.go:72 +0xfc

```

**Comment by ignoramous** [comment]
L124

```
22 September 2024, 03:20:00: F c.sendRequest: CacheBlockFreeDNS-over-HTTPS [11] runtime error: invalid memory address or nil pointer dereference
 (#1)
22 September 2024, 03:20:00: goroutine 38395 [running]:
github.com/celzero/firestack/intra/log.(*simpleLogger).Stack(0x4000224230, 0x0, {0x400a8ff900?, 0x400a8ff780?}, {0x400a380000, 0x80000, 0x80000})
	/home/jitpack/build/intra/log/logger.go:398 +0x2c8
github.com/celzero/firestack/intra/log.C({0x400a8ff780, 0x72}, {0x400a380000, 0x80000, 0x80000})
	/home/jitpack/build/intra/log/log.go:137 +0xf8
github.com/celzero/firestack/intra/core.trace(0x4000224230?, {0x400a8ff780, 0x72})
	/home/jitpack/build/intra/core/dontpanic.go:101 +0x19c
github.com/celzero/firestack/intra/core.Recover(0xb, {0x40091928d0, 0x2b})
	/home/jitpack/build/intra/core/dontpanic.go:74 +0x13c
panic({0x7dc4d51b80?, 0x7dc52b7ee0?})
	/home/jitpack/golang/go/src/runtime/panic.go:785 +0x124
github.com/miekg/dns.(*OPT).len(0x40097a3540, 0x11?, 0xc?)
	/tmp/gomobile-work-3018107916/pkg/mod/github.com/miekg/dns@v1.1.49/edns.go:130 +0x64
github.com/miekg/dns.msgLenWithCompressionMap(0x400ab467e0, 0x400b292240)
	/tmp/gomobile-work-3018107916/pkg/mod/github.com/miekg/dns@v1.1.49/msg.go:982 +0x1a8
github.com/miekg/dns.(*Msg).Len(0x400ab467e0)
	/tmp/gomobile-work-3018107916/pkg/mod/github.com/miekg/dns@v1.1.49/msg.go:958 +0x58
github.com/celzero/firestack/intra/doh.padQuery(0x400ab467e0)
	/home/jitpack/build/intra/doh/padding.go:124 +0x25c
github.com/celzero/firestack/intra/doh.(*transport).doDoh(0x40087b8200, {0x400948663c, 0x4}, 0x400ab467e0)
	/home/jitpack/build/intra/doh/doh.go:343 +0x44
github.com/celzero/firestack/intra/doh.(*transport).Query(0x40087b8200, {0x4009486638, 0x8}, 0x400ab467e0, 0x400940c780)
	/home/jitpack/build/intra/doh/doh.go:609 +0xa8
github.com/celzero/firestack/intra/dnsx.Req({0x7dc4e49b20, 0x40087b8200}, {0x4009486638, 0x8}, 0x400ab467e0, 0x400940c780)
	/home/jitpack/build/intra/dnsx/alg.go:1101 +0xd8
github.com/celzero/firestack/intra/dnsx.(*ctransport).fetch.func1.1()
	/home/jitpack/build/intra/dnsx/cacher.go:335 +0x5c
github.com/celzero/firestack/intra/core.(*Barrier[...]).Do(0x7dc4e52220, {0x40092069f0, 0x12}, 0x4008a18ee0)
	/home/jitpack/build/intra/core/barrier.go:118 +0x1bc
github.com/celzero/firestack/intra/dnsx.(*ctransport).fetch.func1(0x400940c780)
	/home/jitpack/build/intra/dnsx/cacher.go:333 +0x164
github.com/celzero/firestack/intra/dnsx.(*ctransport).fetch.func2()
	/home/jitpack/build/intra/dnsx/cacher.go:404 +0x38
github.com/celzero/firestack/intra/core.Gx.func1()
	/home/jitpack/build/intra/core/async.go:55 +0x5c
created by github.com/celzero/firestack/intra/core.Gx in goroutine 38392
	/home/jitpack/build/intra/core/async.go:52 +0x7c
```
