### ISSUE TITLE
panic: tcpip/link/sniffer.(*Endpoint).DumpPacket

### ISSUE THREAD

**Issue by ignoramous** [celzero/firestack#99]
```jsx
05 October 2024, 05:55:01: F tcp.forward:79a5632d879b2cec [0] multiple Read calls return no data or error
 (#1)
05 October 2024, 05:55:01: goroutine 46492 [running]:
github.com/celzero/firestack/intra/log.(*simpleLogger).Stack(0x4000230230, 0x0, {0x4000a02280?, 0x4000a02000?}, {0x4000f3a000, 0x80000, 0x80000})
	/home/jitpack/build/intra/log/logger.go:398 +0x2c8
github.com/celzero/firestack/intra/log.C({0x4000a02000, 0x4d}, {0x4000f3a000, 0x80000, 0x80000})
	/home/jitpack/build/intra/log/log.go:137 +0xf8
github.com/celzero/firestack/intra/core.trace(0x4000230230?, {0x4000a02000, 0x4d})
	/home/jitpack/build/intra/core/dontpanic.go:101 +0x19c
github.com/celzero/firestack/intra/core.Recover(0x0, {0x40004e9e80, 0x1c})
	/home/jitpack/build/intra/core/dontpanic.go:74 +0x13c
panic({0x719674a100?, 0x7196ccdc00?})
	/home/jitpack/golang/go/src/runtime/panic.go:785 +0x124
gvisor.dev/gvisor/pkg/tcpip/link/sniffer.(*Endpoint).DumpPacket(0x40002d4620, 0x400001a570?, 0x676048?, 0x71963f51a8?, 0x8?)
	/tmp/gomobile-work-238064461/pkg/mod/gvisor.dev/gvisor@v0.0.0-20241003235444-a89be6af9e4c/pkg/tcpip/link/sniffer/sniffer.go:171 +0x110
gvisor.dev/gvisor/pkg/tcpip/link/sniffer.(*Endpoint).WritePackets(0x40002d4620, {{0x400001a570, 0x1, 0x1}})
	/tmp/gomobile-work-238064461/pkg/mod/gvisor.dev/gvisor@v0.0.0-20241003235444-a89be6af9e4c/pkg/tcpip/link/sniffer/sniffer.go:181 +0x54
gvisor.dev/gvisor/pkg/tcpip/stack.(*delegatingQueueingDiscipline).WritePacket(0x4000032c30, 0x40006b4c80)
	/tmp/gomobile-work-238064461/pkg/mod/gvisor.dev/gvisor@v0.0.0-20241003235444-a89be6af9e4c/pkg/tcpip/stack/nic.go:159 +0xa4
gvisor.dev/gvisor/pkg/tcpip/stack.(*nic).writeRawPacket(0x4000204488, 0x40006b4c80)
	/tmp/gomobile-work-238064461/pkg/mod/gvisor.dev/gvisor@v0.0.0-20241003235444-a89be6af9e4c/pkg/tcpip/stack/nic.go:426 +0x5c
gvisor.dev/gvisor/pkg/tcpip/stack.(*nic).writePacket(0x4000204488, 0x40006b4c80)
	/tmp/gomobile-work-238064461/pkg/mod/gvisor.dev/gvisor@v0.0.0-20241003235444-a89be6af9e4c/pkg/tcpip/stack/nic.go:408 +0x40
gvisor.dev/gvisor/pkg/tcpip/stack.(*nic).WritePacket(0x4000204488, 0x40002378c0, 0x40006b4c80)
	/tmp/gomobile-work-238064461/pkg/mod/gvisor.dev/gvisor@v0.0.0-20241003235444-a89be6af9e4c/pkg/tcpip/stack/nic.go:369 +0x124
gvisor.dev/gvisor/pkg/tcpip/network/ipv6.(*endpoint).writePacket(0x4000396008, 0x40002378c0, 0x40006b4c80, 0x6, 0x0?)
	/tmp/gomobile-work-238064461/pkg/mod/gvisor.dev/gvisor@v0.0.0-20241003235444-a89be6af9e4c/pkg/tcpip/network/ipv6/ipv6.go:891 +0x3d4
gvisor.dev/gvisor/pkg/tcpip/network/ipv6.(*endpoint).WritePacket(0x4000396008, 0x40002378c0, {0x86dd?, 0x0?, 0x0?, 0x0?}, 0x40006b4c80)
	/tmp/gomobile-work-238064461/pkg/mod/gvisor.dev/gvisor@v0.0.0-20241003235444-a89be6af9e4c/pkg/tcpip/network/ipv6/ipv6.go:842 +0x2ac
gvisor.dev/gvisor/pkg/tcpip/stack.(*Route).WritePacket(0x40002378c0, {0x9bff6400?, 0x0?, 0x1?, 0xda?}, 0x40006b4c80)
	/tmp/gomobile-work-238064461/pkg/mod/gvisor.dev/gvisor@v0.0.0-20241003235444-a89be6af9e4c/pkg/tcpip/stack/route.go:507 +0x80
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.sendTCP(0x40002378c0, {{0x1bb, {{0x0, 0x64, 0xff, 0x9b, 0x0, 0x1, 0xda, 0x19, ...}, ...}, ...}, ...}, ...)
	/tmp/gomobile-work-238064461/pkg/mod/gvisor.dev/gvisor@v0.0.0-20241003235444-a89be6af9e4c/pkg/tcpip/transport/tcp/connect.go:932 +0x168
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*Endpoint).sendTCP(0x400023ca08, 0x71963bdea0?, {{0x1bb, {{0x0, 0x64, 0xff, 0x9b, 0x0, 0x1, 0xda, ...}, ...}, ...}, ...}, ...)
	/tmp/gomobile-work-238064461/pkg/mod/gvisor.dev/gvisor@v0.0.0-20241003235444-a89be6af9e4c/pkg/tcpip/transport/tcp/connect.go:830 +0x90
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*Endpoint).sendRaw(0x400023ca08, 0x40006b4c80, 0x10, 0x90394b0d, 0xe9ae88b6, 0x800)
	/tmp/gomobile-work-238064461/pkg/mod/gvisor.dev/gvisor@v0.0.0-20241003235444-a89be6af9e4c/pkg/tcpip/transport/tcp/connect.go:1005 +0x254
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*sender).sendSegmentFromPacketBuffer(0x400021ca88, 0x4000a0fb80, 0x10, 0x90394b0d)
	/tmp/gomobile-work-238064461/pkg/mod/gvisor.dev/gvisor@v0.0.0-20241003235444-a89be6af9e4c/pkg/tcpip/transport/tcp/snd.go:1749 +0xd8
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*sender).sendSegment(0x400021ca88, 0x4000706c00)
	/tmp/gomobile-work-238064461/pkg/mod/gvisor.dev/gvisor@v0.0.0-20241003235444-a89be6af9e4c/pkg/tcpip/transport/tcp/snd.go:1710 +0x1a0
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*sender).maybeSendSegment(0x400021ca88, 0x4000706c00, 0x0?, 0x706e00?)
	/tmp/gomobile-work-238064461/pkg/mod/gvisor.dev/gvisor@v0.0.0-20241003235444-a89be6af9e4c/pkg/tcpip/transport/tcp/snd.go:914 +0x1f4
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*sender).sendData(0x400021ca88)
	/tmp/gomobile-work-238064461/pkg/mod/gvisor.dev/gvisor@v0.0.0-20241003235444-a89be6af9e4c/pkg/tcpip/transport/tcp/snd.go:1031 +0x1d0
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*Endpoint).sendData(0x1bb?, 0x19da01009bff6400?)
	/tmp/gomobile-work-238064461/pkg/mod/gvisor.dev/gvisor@v0.0.0-20241003235444-a89be6af9e4c/pkg/tcpip/transport/tcp/connect.go:1030 +0x40
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*Endpoint).shutdownLocked(0x400023ca08, 0x13?)
	/tmp/gomobile-work-238064461/pkg/mod/gvisor.dev/gvisor@v0.0.0-20241003235444-a89be6af9e4c/pkg/tcpip/transport/tcp/endpoint.go:2573 +0x490
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*Endpoint).closeLocked(0x400023ca08)
	/tmp/gomobile-work-238064461/pkg/mod/gvisor.dev/gvisor@v0.0.0-20241003235444-a89be6af9e4c/pkg/tcpip/transport/tcp/endpoint.go:1093 +0xa0
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*Endpoint).Close(0x400023ca08)
	/tmp/gomobile-work-238064461/pkg/mod/gvisor.dev/gvisor@v0.0.0-20241003235444-a89be6af9e4c/pkg/tcpip/transport/tcp/endpoint.go:1063 +0x30
gvisor.dev/gvisor/pkg/tcpip/adapters/gonet.(*TCPConn).Close(...)
	/tmp/gomobile-work-238064461/pkg/mod/gvisor.dev/gvisor@v0.0.0-20241003235444-a89be6af9e4c/pkg/tcpip/adapters/gonet/gonet.go:418
github.com/celzero/firestack/intra/core.CloseConn({0x4000035c38?, 0x719680a5c0?, 0x4000035cb8?})
	/home/jitpack/build/intra/core/closer.go:111 +0xe0
github.com/celzero/firestack/intra/core.CloseOp({0x71968481a0, 0x4000668720}, 0x3)
	/home/jitpack/build/intra/core/closer.go:144 +0x3b8
github.com/celzero/firestack/intra/core.Close(...)
	/home/jitpack/build/intra/core/closer.go:128
github.com/celzero/firestack/intra/netstack.(*GTCPConn).Abort(0x4000ba2620)
	/home/jitpack/build/intra/netstack/tcp.go:304 +0xc0
github.com/celzero/firestack/intra/netstack.(*GTCPConn).Close(0x7196810840?)
	/home/jitpack/build/intra/netstack/tcp.go:308 +0x1c
github.com/celzero/firestack/intra/core.CloseConn({0x40000dcb60?, 0x4000144930?, 0x40002ff120?})
	/home/jitpack/build/intra/core/closer.go:119 +0x1f8
github.com/celzero/firestack/intra/core.(*cm).delLocked(0x4000144960, {0x40002ff120, 0x10})
	/home/jitpack/build/intra/core/connmap.go:96 +0x9c
github.com/celzero/firestack/intra/core.(*cm).Untrack(0x4000144960, {0x40002ff120, 0x10})
	/home/jitpack/build/intra/core/connmap.go:69 +0x68
panic({0x719674a100?, 0x7196ccdc00?})
	/home/jitpack/golang/go/src/runtime/panic.go:785 +0x124
gvisor.dev/gvisor/pkg/tcpip/link/sniffer.(*Endpoint).DumpPacket(0x40002d4620, 0x400001a568?, 0x35fd8?, 0x71963f51a8?, 0x8?)
	/tmp/gomobile-work-238064461/pkg/mod/gvisor.dev/gvisor@v0.0.0-20241003235444-a89be6af9e4c/pkg/tcpip/link/sniffer/sniffer.go:171 +0x110
gvisor.dev/gvisor/pkg/tcpip/link/sniffer.(*Endpoint).WritePackets(0x40002d4620, {{0x400001a568, 0x1, 0x1}})
	/tmp/gomobile-work-238064461/pkg/mod/gvisor.dev/gvisor@v0.0.0-20241003235444-a89be6af9e4c/pkg/tcpip/link/sniffer/sniffer.go:181 +0x54
gvisor.dev/gvisor/pkg/tcpip/stack.(*delegatingQueueingDiscipline).WritePacket(0x4000032c30, 0x40006b4c80)
	/tmp/gomobile-work-238064461/pkg/mod/gvisor.dev/gvisor@v0.0.0-20241003235444-a89be6af9e4c/pkg/tcpip/stack/nic.go:159 +0xa4
gvisor.dev/gvisor/pkg/tcpip/stack.(*nic).writeRawPacket(0x4000204488, 0x40006b4c80)
	/tmp/gomobile-work-238064461/pkg/mod/gvisor.dev/gvisor@v0.0.0-20241003235444-a89be6af9e4c/pkg/tcpip/stack/nic.go:426 +0x5c
gvisor.dev/gvisor/pkg/tcpip/stack.(*nic).writePacket(0x4000204488, 0x40006b4c80)
	/tmp/gomobile-work-238064461/pkg/mod/gvisor.dev/gvisor@v0.0.0-20241003235444-a89be6af9e4c/pkg/tcpip/stack/nic.go:408 +0x40
gvisor.dev/gvisor/pkg/tcpip/stack.(*nic).WritePacket(0x4000204488, 0x40002378c0, 0x40006b4c80)
	/tmp/gomobile-work-238064461/pkg/mod/gvisor.dev/gvisor@v0.0.0-20241003235444-a89be6af9e4c/pkg/tcpip/stack/nic.go:369 +0x124
gvisor.dev/gvisor/pkg/tcpip/network/ipv6.(*endpoint).writePacket(0x4000396008, 0x40002378c0, 0x40006b4c80, 0x6, 0x0?)
	/tmp/gomobile-work-238064461/pkg/mod/gvisor.dev/gvisor@v0.0.0-20241003235444-a89be6af9e4c/pkg/tcpip/network/ipv6/ipv6.go:891 +0x3d4
gvisor.dev/gvisor/pkg/tcpip/network/ipv6.(*endpoint).WritePacket(0x4000396008, 0x40002378c0, {0x86dd?, 0x0?, 0x0?, 0x0?}, 0x40006b4c80)
	/tmp/gomobile-work-238064461/pkg/mod/gvisor.dev/gvisor@v0.0.0-20241003235444-a89be6af9e4c/pkg/tcpip/network/ipv6/ipv6.go:842 +0x2ac
gvisor.dev/gvisor/pkg/tcpip/stack.(*Route).WritePacket(0x40002378c0, {0x9bff6400?, 0x0?, 0x1?, 0xda?}, 0x40006b4c80)
	/tmp/gomobile-work-238064461/pkg/mod/gvisor.dev/gvisor@v0.0.0-20241003235444-a89be6af9e4c/pkg/tcpip/stack/route.go:507 +0x80
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.sendTCP(0x40002378c0, {{0x1bb, {{0x0, 0x64, 0xff, 0x9b, 0x0, 0x1, 0xda, 0x19, ...}, ...}, ...}, ...}, ...)
	/tmp/gomobile-work-238064461/pkg/mod/gvisor.dev/gvisor@v0.0.0-20241003235444-a89be6af9e4c/pkg/tcpip/transport/tcp/connect.go:932 +0x168
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*Endpoint).sendTCP(0x400023ca08, 0x71963bdea0?, {{0x1bb, {{0x0, 0x64, 0xff, 0x9b, 0x0, 0x1, 0xda, ...}, ...}, ...}, ...}, ...)
	/tmp/gomobile-work-238064461/pkg/mod/gvisor.dev/gvisor@v0.0.0-20241003235444-a89be6af9e4c/pkg/tcpip/transport/tcp/connect.go:830 +0x90
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*Endpoint).sendRaw(0x400023ca08, 0x40006b4c80, 0x10, 0x90394b0d, 0xe9ae88b6, 0x800)
	/tmp/gomobile-work-238064461/pkg/mod/gvisor.dev/gvisor@v0.0.0-20241003235444-a89be6af9e4c/pkg/tcpip/transport/tcp/connect.go:1005 +0x254
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*sender).sendSegmentFromPacketBuffer(0x400021ca88, 0x4000a0fb80, 0x10, 0x90394b0d)
	/tmp/gomobile-work-238064461/pkg/mod/gvisor.dev/gvisor@v0.0.0-20241003235444-a89be6af9e4c/pkg/tcpip/transport/tcp/snd.go:1749 +0xd8
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*sender).sendSegment(0x400021ca88, 0x4000706c00)
	/tmp/gomobile-work-238064461/pkg/mod/gvisor.dev/gvisor@v0.0.0-20241003235444-a89be6af9e4c/pkg/tcpip/transport/tcp/snd.go:1710 +0x1a0
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*sender).maybeSendSegment(0x400021ca88, 0x4000706c00, 0x578?, 0x903e812d?)
	/tmp/gomobile-work-238064461/pkg/mod/gvisor.dev/gvisor@v0.0.0-20241003235444-a89be6af9e4c/pkg/tcpip/transport/tcp/snd.go:914 +0x1f4
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*sender).sendData(0x400021ca88)
	/tmp/gomobile-work-238064461/pkg/mod/gvisor.dev/gvisor@v0.0.0-20241003235444-a89be6af9e4c/pkg/tcpip/transport/tcp/snd.go:1031 +0x1d0
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*Endpoint).sendData(0x400023ca08?, 0x0?)
	/tmp/gomobile-work-238064461/pkg/mod/gvisor.dev/gvisor@v0.0.0-20241003235444-a89be6af9e4c/pkg/tcpip/transport/tcp/connect.go:1030 +0x40
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*Endpoint).Write(0x400023ca08, {0x719684a3f8, 0x4000193770}, {0x0, 0x0, 0x0, 0x0, {0x0, 0x0, 0x0, ...}})
	/tmp/gomobile-work-238064461/pkg/mod/gvisor.dev/gvisor@v0.0.0-20241003235444-a89be6af9e4c/pkg/tcpip/transport/tcp/endpoint.go:1661 +0xd8
gvisor.dev/gvisor/pkg/tcpip/adapters/gonet.(*TCPConn).Write(0x4000668720, {0x4000920000, 0x10000, 0x10000})
	/tmp/gomobile-work-238064461/pkg/mod/gvisor.dev/gvisor@v0.0.0-20241003235444-a89be6af9e4c/pkg/tcpip/adapters/gonet/gonet.go:389 +0x1cc
github.com/celzero/firestack/intra/netstack.(*GTCPConn).Write(0x400020d4a0?, {0x4000920000?, 0x10000?, 0x10000?})
	/home/jitpack/build/intra/netstack/tcp.go:253 +0x8c
io.copyBuffer({0x721fbc1268, 0x4000ba2620}, {0x721fbc1288, 0x400020d4a0}, {0x4000920000, 0x10000, 0x10000})
	/home/jitpack/golang/go/src/io/io.go:431 +0x1cc
io.CopyBuffer({0x721fbc1268?, 0x4000ba2620?}, {0x721fbc1288?, 0x400020d4a0?}, {0x4000920000?, 0x7196849ec0?, 0x7196849ec0?})
	/home/jitpack/golang/go/src/io/io.go:402 +0x38
github.com/celzero/firestack/intra/core.Pipe({0x721fbc1268, 0x4000ba2620}, {0x721fbc1288, 0x400020d4a0})
	/home/jitpack/build/intra/core/cp.go:36 +0x1cc
github.com/celzero/firestack/intra.download({0x40002ff120, 0x10}, {0x7196854ab0, 0x4000ba2620}, {0x7196856eb8, 0x400020d4a0})
	/home/jitpack/build/intra/common.go:54 +0xac
github.com/celzero/firestack/intra.forward({0x7196854ab0, 0x4000ba2620}, {0x7196856eb8, 0x400020d4a0}, 0x40002d4310, 0x400026e310, 0x40000ade00)
	/home/jitpack/build/intra/common.go:70 +0x100
github.com/celzero/firestack/intra.(*tcpHandler).handle.func1()
	/home/jitpack/build/intra/tcp.go:335 +0x84
github.com/celzero/firestack/intra/core.Go.func1()
	/home/jitpack/build/intra/core/async.go:18 +0x5c
created by github.com/celzero/firestack/intra/core.Go in goroutine 46490
	/home/jitpack/build/intra/core/async.go:15 +0x7c
```

Any err returned by sniffer.writer.Write panics.

https://github.com/celzero/firestack/blob/e694da7d48f6071676bbb1f8ac8cad31286cc0c8/tunnel/tunnel.go#L104-L117

**Comment by ignoramous** [comment]
Commits: check #100
